"object"!==typeof JSON2&&(JSON2={});
(function(){function a(a){return 10>a?"0"+a:a}function r(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=E[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(f,c){var b,e,u,h=m,k=c[f];k&&"object"===typeof k&&(b=k,u=Object.prototype.toString.apply(b),k="[object Date]"===u?isFinite(b.valueOf())?b.getUTCFullYear()+"-"+a(b.getUTCMonth()+1)+"-"+a(b.getUTCDate())+"T"+a(b.getUTCHours())+":"+a(b.getUTCMinutes())+":"+a(b.getUTCSeconds())+
"Z":null:"[object String]"===u||"[object Number]"===u||"[object Boolean]"===u?b.valueOf():"[object Array]"!==u&&"function"===typeof b.toJSON?b.toJSON(f):b);"function"===typeof p&&(k=p.call(c,f,k));switch(typeof k){case "string":return r(k);case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);case "object":if(!k)return"null";m+=w;var v=[];if("[object Array]"===Object.prototype.toString.apply(k)){var n=k.length;for(b=0;b<n;b+=1)v[b]=l(b,k)||"null";u=0===v.length?
"[]":m?"[\n"+m+v.join(",\n"+m)+"\n"+h+"]":"["+v.join(",")+"]";m=h;return u}if(p&&"object"===typeof p)for(n=p.length,b=0;b<n;b+=1)"string"===typeof p[b]&&(e=p[b],(u=l(e,k))&&v.push(r(e)+(m?": ":":")+u));else for(e in k)Object.prototype.hasOwnProperty.call(k,e)&&(u=l(e,k))&&v.push(r(e)+(m?": ":":")+u);u=0===v.length?"{}":m?"{\n"+m+v.join(",\n"+m)+"\n"+h+"}":"{"+v.join(",")+"}";m=h;return u}}var n=RegExp("[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]",
"g"),f=RegExp('[\\\\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]',"g"),m,w,E={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},p;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(a,c,b){var e;w=m="";if("number"===typeof b)for(e=0;e<b;e+=1)w+=" ";else"string"===typeof b&&(w=b);if((p=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON2.stringify");
return l("",{"":a})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(a,c){function b(a,e){var u,f,m=a[e];if(m&&"object"===typeof m)for(u in m)Object.prototype.hasOwnProperty.call(m,u)&&(f=b(m,u),void 0!==f?m[u]=f:delete m[u]);return c.call(a,e,m)}var e;a=String(a);n.lastIndex=0;n.test(a)&&(a=a.replace(n,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',
"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return e=eval("("+a+")"),"function"===typeof c?b({"":e},""):e;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof PiwikNew&&(PiwikNew=function(){function a(g){return"undefined"!==typeof g}function r(g){return"object"===typeof g}function l(g){return"string"===typeof g||g instanceof String}function n(){var g;for(g=0;g<arguments.length;g+=1){var a=arguments[g],b=a.shift();l(b)?F[b].apply(F,a):b.apply(F,a)}}function f(a,b,c,pa){if(a.addEventListener)return a.addEventListener(b,c,pa),!0;if(a.attachEvent)return a.attachEvent("on"+b,c);a["on"+b]=c}function m(a,b){var g="",c,e;for(c in J)Object.prototype.hasOwnProperty.call(J,
c)&&(e=J[c][a],"function"===typeof e&&(g+=e(b)));return g}function w(){var a;if(!aa)for(aa=!0,m("load"),a=0;a<qa.length;a++)qa[a]();return!0}function E(a,b){var g=t.createElement("script");g.type="text/javascript";g.src=a;g.readyState?g.onreadystatechange=function(){var a=this.readyState;if("loaded"===a||"complete"===a)g.onreadystatechange=null,b()}:g.onload=b;t.getElementsByTagName("head")[0].appendChild(g)}function p(){var a="";try{a=q.top.document.referrer}catch(Ja){if(q.parent)try{a=q.parent.document.referrer}catch(Ka){a=
""}}""===a&&(a=t.referrer);return a}function v(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function c(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function b(a,b){var c=RegExp("[\\?&#]"+b+"=([^&#]*)").exec(a);return c?La(c[1]):""}function e(a){var b=function(a,b){return a<<b|a>>>32-b},c=function(a){var b="",g;for(g=7;0<=g;g--)b+=(a>>>4*g&15).toString(16);return b},g,e=[],u=1732584193,f=4023233417,m=2562383102,t=271733878,q=3285377520,l=[];a=Oa(B(a));var h=a.length;
for(g=0;g<h-3;g+=4){var p=a.charCodeAt(g)<<24|a.charCodeAt(g+1)<<16|a.charCodeAt(g+2)<<8|a.charCodeAt(g+3);l.push(p)}switch(h&3){case 0:g=2147483648;break;case 1:g=a.charCodeAt(h-1)<<24|8388608;break;case 2:g=a.charCodeAt(h-2)<<24|a.charCodeAt(h-1)<<16|32768;break;case 3:g=a.charCodeAt(h-3)<<24|a.charCodeAt(h-2)<<16|a.charCodeAt(h-1)<<8|128}for(l.push(g);14!==(l.length&15);)l.push(0);l.push(h>>>29);l.push(h<<3&4294967295);for(a=0;a<l.length;a+=16){for(g=0;16>g;g++)e[g]=l[a+g];for(g=16;79>=g;g++)e[g]=
b(e[g-3]^e[g-8]^e[g-14]^e[g-16],1);p=u;h=f;var v=m,k=t,r=q;for(g=0;19>=g;g++){var n=b(p,5)+(h&v|~h&k)+r+e[g]+1518500249&4294967295;r=k;k=v;v=b(h,30);h=p;p=n}for(g=20;39>=g;g++)n=b(p,5)+(h^v^k)+r+e[g]+1859775393&4294967295,r=k,k=v,v=b(h,30),h=p,p=n;for(g=40;59>=g;g++)n=b(p,5)+(h&v|h&k|v&k)+r+e[g]+2400959708&4294967295,r=k,k=v,v=b(h,30),h=p,p=n;for(g=60;79>=g;g++)n=b(p,5)+(h^v^k)+r+e[g]+3395469782&4294967295,r=k,k=v,v=b(h,30),h=p,p=n;u=u+p&4294967295;f=f+h&4294967295;m=m+v&4294967295;t=t+k&4294967295;
q=q+r&4294967295}n=c(u)+c(f)+c(m)+c(t)+c(q);return n.toLowerCase()}function u(a,e,h){if("translate.googleusercontent.com"===a)""===h&&(h=e),e=b(e,"u"),a=c(e);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))e=t.links[0].href,a=c(e);return[a,e,h]}function h(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function k(b){b=b&&b.text?b.text:b;if(!l(b)){var c=t.getElementsByTagName("title");c&&a(c[0])&&(b=c[0].text)}return b}
function K(a,b){if(b)return b;"piwik.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function gb(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idsite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(t.referrer);if(b){if(b[1]!==String(a))return!1;q.name="Piwik_Overlay###"+b[2]+"###"+b[3]}a=q.name.split("###");return 3===a.length&&"Piwik_Overlay"===a[0]}function jb(a,b,c){var e=q.name.split("###"),g=e[1],h=e[2],u=K(a,b);E(u+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(u,
c,g,h)})}function G(g,n){function w(d,a,b,c,e,g){if(!R){var x;b&&(x=new Date,x.setTime(x.getTime()+b));t.cookie=d+"="+B(a)+(b?";expires="+x.toGMTString():"")+";path="+(c||"/")+(e?";domain="+e:"")+(g?";secure":"")}}function K(d){return R?0:(d=RegExp("(^|;)[ ]*"+d+"=([^;]*)").exec(t.cookie))?La(d[2]):0}function A(d){var a;return Pa?(a=/#.*/,d.replace(a,"")):d}function E(d){var a;for(a=0;a<ha.length;a++){var b=h(ha[a].toLowerCase());if(d===b)return!0;if("."===b.slice(0,1)){if(d===b.slice(1))return!0;
var c=d.length-b.length;if(0<c&&d.slice(c)===b)return!0}}return!1}function J(d){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=ba+(0>ba.indexOf("?")?"?":"&")+d;a.onload=function(){};d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(a,d)}function G(d){try{var a=q.XMLHttpRequest?new q.XMLHttpRequest:q.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;a.open("POST",ba,!0);a.onreadystatechange=function(){4===this.readyState&&200!==this.status&&
J(d)};a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");a.send(d)}catch(L){J(d)}}function X(d,a){var b=new Date;ta||("POST"===Qa?G(d):J(d),M=b.getTime()+a)}function Ja(){if(R)return"0";if(!a(y.cookieEnabled)){var d=I+"testcookie";w(d,"1");return"1"===K(d)?"1":"0"}return y.cookieEnabled?"1":"0"}function F(){Ra((O||ua)+(P||"/")).slice(0,4)}function ra(){var d=K(I+"cvar");return d.length&&(d=JSON2.parse(d),r(d))?d:{}}function C(){va=(new Date).getTime()}function sa(){var d=
Math.round((new Date).getTime()/1E3),a=K(I+"id");a?(d=a.split("."),d.unshift("0")):(wa||(wa=Ra((y.userAgent||"")+(y.platform||"")+JSON2.stringify(Q)+d).slice(0,16)),d=["1",wa,d,0,d,"",""]);return d}function Y(){var d=K(I+"ref");if(d.length)try{if(d=JSON2.parse(d),r(d))return d}catch(x){}return["","",0,""]}function fa(){var d=R;R=!1;w(I+"id","",-86400,P,O);w(I+"ses","",-86400,P,O);w(I+"cvar","",-86400,P,O);w(I+"ref","",-86400,P,O);R=d}function Z(d,x,e,g){var L=new Date,h=Math.round(L.getTime()/1E3),
u=H,f=I+"ses",p=I+"ref",v=I+"cvar",k=sa(),l=K(f),U=Y(),q=ia||Sa;R&&fa();if(ta)return"";var n=k[0],r=k[1],y=k[2],z=k[3],C=k[4],J=k[5];a(k[6])||(k[6]="");k=k[6];a(g)||(g="");var F=t.characterSet||t.charset;F&&"utf-8"!==F.toLowerCase()||(F=null);var G=U[0],M=U[1],N=U[2],V=U[3];if(!l){z++;J=C;if(!xa||!G.length){for(D in ja)if(Object.prototype.hasOwnProperty.call(ja,D)&&(G=b(q,ja[D]),G.length))break;for(D in ka)if(Object.prototype.hasOwnProperty.call(ka,D)&&(M=b(q,ka[D]),M.length))break}C=c(ca);l=V.length?
c(V):"";!C.length||E(C)||xa&&l.length&&!E(l)||(V=ca);if(V.length||G.length)N=h,U=[G,M,N,A(V.slice(0,1024))],w(p,JSON2.stringify(U),Ta,P,O)}d+="&idsite="+la+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+L.getHours()+"&m="+L.getMinutes()+"&s="+L.getSeconds()+"&url="+B(A(q))+(ca.length?"&urlref="+B(A(ca)):"")+"&_id="+r+"&_idts="+y+"&_idvc="+z+"&_idn="+n+(G.length?"&_rcn="+B(G):"")+(M.length?"&_rck="+B(M):"")+"&_refts="+N+"&_viewts="+J+(String(k).length?"&_ects="+k:"")+(String(V).length?"&_ref="+
B(A(V.slice(0,1024))):"")+(F?"&cs="+B(F):"")+(K("myvne_user_id").length?"&myvne_user_id="+K("myvne_user_id"):"")+(K("fosp_vid").length?"&fosp_vid="+K("fosp_vid"):"");L=JSON2.stringify(W);2<L.length&&(d+="&cvar="+B(L));for(D in Q)Object.prototype.hasOwnProperty.call(Q,D)&&(d+="&"+D+"="+Q[D]);x?d+="&data="+B(JSON2.stringify(x)):S&&(d+="&data="+B(JSON2.stringify(S)));if(H){x=JSON2.stringify(H);2<x.length&&(d+="&_cvar="+B(x));for(D in u)Object.prototype.hasOwnProperty.call(u,D)&&(""!==H[D][0]&&""!==H[D][1]||
delete H[D]);w(v,JSON2.stringify(H),ya,P,O)}za&&Aa?d+="&gt_ms="+Aa:za&&T&&T.timing&&T.timing.requestStart&&T.timing.responseEnd&&(d+="&gt_ms="+(T.timing.responseEnd-T.timing.requestStart));var D=z;g=a(g)&&String(g).length?g:k;w(I+"id",r+"."+y+"."+D+"."+h+"."+J+"."+g,Ua,P,O);w(f,"*",ya,P,O);d+=m(e);Ba.length&&(d+="&"+Ba);Ca&&(d+="&fosp_id="+Ca);Da&&(d+="&fosp_loc="+Da);return d}function Ma(d,b,c,e,g,h){var x="idgoal=0",L,u=new Date,k=[],f;String(d).length&&(x+="&ec_id="+B(d),L=Math.round(u.getTime()/
1E3));x+="&revenue="+b;String(c).length&&(x+="&ec_st="+c);String(e).length&&(x+="&ec_tx="+e);String(g).length&&(x+="&ec_sh="+g);String(h).length&&(x+="&ec_dt="+h);if(z){for(f in z)Object.prototype.hasOwnProperty.call(z,f)&&(a(z[f][1])||(z[f][1]=""),a(z[f][2])||(z[f][2]=""),a(z[f][3])&&0!==String(z[f][3]).length||(z[f][3]=0),a(z[f][4])&&0!==String(z[f][4]).length||(z[f][4]=1),k.push(z[f]));x+="&ec_items="+B(JSON2.stringify(k))}x=Z(x,S,"ecommerce",L);X(x,N)}function ib(d,a){var b=new Date,x=Z("action_name="+
B(k(d||Va)),a,"log");X(x,N);Ea&&da&&!Wa&&(Wa=!0,f(t,"click",C),f(t,"mouseup",C),f(t,"mousedown",C),f(t,"mousemove",C),f(t,"mousewheel",C),f(q,"DOMMouseScroll",C),f(q,"scroll",C),f(t,"keypress",C),f(t,"keydown",C),f(t,"keyup",C),f(q,"resize",C),f(q,"focus",C),f(q,"blur",C),va=b.getTime(),setTimeout(function kb(){var d=new Date;va+da>d.getTime()&&(Ea<d.getTime()&&(d=Z("ping=1",a,"ping"),X(d,N)),setTimeout(kb,da))},da))}function Na(d,a,b){d=Z(a+"="+B(A(d)),b,"link");X(d,N)}function ea(d){var a,b,c=["",
"webkit","ms","moz"],e;if(!Xa)for(b=0;b<c.length;b++)if(e=c[b],Object.prototype.hasOwnProperty.call(t,""!==e?e+"Hidden":"hidden")){"prerender"===t[""!==e?e+"VisibilityState":"visibilityState"]&&(a=!0);break}a?f(t,e+"visibilitychange",function lb(){t.removeEventListener(e+"visibilitychange",lb,!1);d()}):d()}function Fa(d,a){var b,c="(^| )(piwik[_-]"+a;if(d)for(b=0;b<d.length;b++)c+="|"+d[b];return RegExp(c+")( |$)")}function Ya(d){for(var b,e,g;null!==(e=d.parentNode)&&a(e)&&"A"!==(g=d.tagName.toUpperCase())&&
"AREA"!==g;)d=e;if(a(d.href)&&(e=d.hostname||c(d.href),b=e.toLowerCase(),e=d.href.replace(e,b),!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(e))){d=d.className;g=e;b=E(b);var h=Fa(Za,"download"),f=Fa($a,"link"),u=RegExp("\\.("+Ga+")([?&#]|$)","i");if(d=f.test(d)?"link":h.test(d)||u.test(g)?"download":b?0:"link")e=Oa(e),Na(e,d)}}function Ha(d){d=d||q.event;var a=d.which||d.button,b=d.target||d.srcElement;"click"===d.type?b&&Ya(b):"mousedown"===d.type?1!==a&&2!==a||!b?
ma=na=null:(ma=a,na=b):"mouseup"===d.type&&(a===ma&&b===na&&Ya(b),ma=na=null)}function ab(d,a){a?(f(d,"mouseup",Ha,!1),f(d,"mousedown",Ha,!1)):f(d,"click",Ha,!1)}function bb(d){if(!cb){cb=!0;var a,b=Fa(db,"ignore"),c=t.links;if(c)for(a=0;a<c.length;a++)b.test(c[a].className)||ab(c[a],d)}}var Ca=null,Da=null,oa={},Ia=u(t.domain,q.location.href,p()),ua=h(Ia[0]),Sa=Ia[1],ca=Ia[2],Qa="GET",ba=g||"",eb="",Ba="",la=n||"",ia,Va=t.title,Ga="7z|aac|ar[cj]|as[fx]|avi|bin|csv|deb|dmg|docx?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",
ha=[ua],db=[],Za=[],$a=[],N=500,Ea,da,Pa,S,ja=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],ka=["pk_kwd","piwik_kwd","utm_term"],I="_pk_",O,P,R=!1,ta,Xa,xa,Ua=63072E6,ya=18E5,Ta=15768E6,za=!0,Aa=0,H=!1,W={},z={},Q={},cb=!1,Wa=!1,va,ma,na,Ra=e,wa;(function(){var d,b,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",
ag:"application/x-silverlight"},e=/Mac OS X.*Safari\//.test(y.userAgent)?q.devicePixelRatio||1:1;if(!/MSIE/.test(y.userAgent)){if(y.mimeTypes&&y.mimeTypes.length)for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(b=y.mimeTypes[c[d]],Q[d]=b&&b.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&a(y.javaEnabled)&&y.javaEnabled()&&(Q.java="1");"function"===typeof q.GearsFactory&&(Q.gears="1");Q.cookie=Ja()}Q.res=fb.width*e+"x"+fb.height*e})();F();m("run",function(d,b){var c=null;if(l(d)&&
!a(oa[d])&&b){if(r(b))c=b;else if(l(b))try{eval("hookObj ="+b)}catch(U){}oa[d]=c}return c});return{hook:oa,getHook:function(d){return oa[d]},getVisitorId:function(){return sa()[1]},getVisitorInfo:function(){return sa()},getAttributionInfo:function(){return Y()},getAttributionCampaignName:function(){return Y()[0]},getAttributionCampaignKeyword:function(){return Y()[1]},getAttributionReferrerTimestamp:function(){return Y()[2]},getAttributionReferrerUrl:function(){return Y()[3]},setTrackerUrl:function(d){ba=
d},setSiteId:function(d){la=d},setCustomData:function(d,a){r(d)?S=d:(S||(S=[]),S[d]=a)},appendToTrackingUrl:function(a){Ba=a},getCustomData:function(){return S},setCustomVariable:function(d,b,c,e){a(e)||(e="visit");if(0<d)if(b=a(b)&&!l(b)?String(b):b,c=a(c)&&!l(c)?String(c):c,b=[b.slice(0,200),c.slice(0,200)],"visit"===e||2===e)!1===H&&(H=ra()),H[d]=b;else if("page"===e||3===e)W[d]=b},getCustomVariable:function(d,b){a(b)||(b="visit");if("page"===b||3===b)var c=W[d];else if("visit"===b||2===b)!1===
H&&(H=ra()),c=H[d];return!a(c)||c&&""===c[0]?!1:c},deleteCustomVariable:function(a,b){this.getCustomVariable(a,b)&&this.setCustomVariable(a,"","",b)},setLinkTrackingTimer:function(a){N=a},setDownloadExtensions:function(a){Ga=a},addDownloadExtensions:function(a){Ga+="|"+a},setDomains:function(a){ha=l(a)?[a]:a;ha.push(ua)},setIgnoreClasses:function(a){db=l(a)?[a]:a},setRequestMethod:function(a){Qa=a||"GET"},setReferrerUrl:function(a){ca=a},setFospId:function(a){Ca=a},setLocation:function(a){Da=a},setCustomUrl:function(a){var b=
Sa,d;v(a)?ia=a:"/"===a.slice(0,1)?ia=v(b)+"://"+c(b)+a:(b=A(b),0<=(d=b.indexOf("?"))&&(b=b.slice(0,d)),(d=b.lastIndexOf("/"))!==b.length-1&&(b=b.slice(0,d+1)),ia=b+a)},setDocumentTitle:function(a){Va=a},setAPIUrl:function(a){eb=a},setDownloadClasses:function(a){Za=l(a)?[a]:a},setLinkClasses:function(a){$a=l(a)?[a]:a},setCampaignNameKey:function(a){ja=l(a)?[a]:a},setCampaignKeywordKey:function(a){ka=l(a)?[a]:a},discardHashTag:function(a){Pa=a},setCookieNamePrefix:function(a){I=a;H=ra()},setCookieDomain:function(a){O=
h(a);F()},setCookiePath:function(a){P=a;F()},setVisitorCookieTimeout:function(a){Ua=1E3*a},setSessionCookieTimeout:function(a){ya=1E3*a},setReferralCookieTimeout:function(a){Ta=1E3*a},setConversionAttributionFirstReferrer:function(a){xa=a},disableCookies:function(){R=!0;Q.cookie="0"},deleteCookies:function(){fa()},setDoNotTrack:function(a){var b=y.doNotTrack||y.msDoNotTrack;(ta=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){ab(a,b)},enableLinkTracking:function(a){aa?bb(a):
qa.push(function(){bb(a)})},disablePerformanceTracking:function(){za=!1},setGenerationTimeMs:function(a){Aa=parseInt(a,10)},setHeartBeatTimer:function(a,b){Ea=(new Date).getTime()+1E3*a;da=1E3*b},killFrame:function(){q.location!==q.top.location&&(q.top.location=q.location)},redirectFile:function(a){"file:"===q.location.protocol&&(q.location=a)},setCountPreRendered:function(a){Xa=a},trackGoal:function(a,b,c){ea(function(){var d=Z("idgoal="+a+(b?"&revenue="+b:""),c,"goal");X(d,N)})},trackLink:function(a,
																																																																																																																												 b,c){ea(function(){Na(a,b,c)})},trackPageView:function(a,b){gb(la)?ea(function(){jb(ba,eb,la)}):ea(function(){ib(a,b)})},trackSiteSearch:function(b,c,e){ea(function(){var d=Z("search="+B(b)+(c?"&search_cat="+B(c):"")+(a(e)?"&search_count="+e:""),void 0,"sitesearch");X(d,N)})},setEcommerceView:function(b,c,e,g){a(e)&&e.length?e instanceof Array&&(e=JSON2.stringify(e)):e="";W[5]=["_pkc",e];a(g)&&String(g).length&&(W[2]=["_pkp",g]);if(a(b)&&b.length||a(c)&&c.length)a(b)&&b.length&&(W[3]=["_pks",b]),
a(c)&&c.length||(c=""),W[4]=["_pkn",c]},addEcommerceItem:function(a,b,c,e,g){a.length&&(z[a]=[a,b,c,e,g])},trackEcommerceOrder:function(b,c,e,g,h,f){String(b).length&&a(c)&&Ma(b,c,e,g,h,f)},trackEcommerceCartUpdate:function(b){a(b)&&Ma("",b,"","","","")}}}var M,J={},t=document,y=navigator,fb=screen,q=window,T=q.performance||q.mozPerformance||q.msPerformance||q.webkitPerformance,aa=!1,qa=[],B=q.encodeURIComponent,La=q.decodeURIComponent,Oa=unescape,A;f(q,"beforeunload",function(){m("unload");if(M){do var a=
new Date;while(a.getTimeAlias()<M)}},!1);(function(){var a;t.addEventListener?f(t,"DOMContentLoaded",function Ka(){t.removeEventListener("DOMContentLoaded",Ka,!1);w()}):t.attachEvent&&(t.attachEvent("onreadystatechange",function pa(){"complete"===t.readyState&&(t.detachEvent("onreadystatechange",pa),w())}),t.documentElement.doScroll&&q===q.top&&function hb(){if(!aa){try{t.documentElement.doScroll("left")}catch(mb){setTimeout(hb,0);return}w()}}());/WebKit/.test(y.userAgent)&&(a=setInterval(function(){if(aa||
/loaded|complete/.test(t.readyState))clearInterval(a),w()},10));f(q,"load",w,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;var F=new G;for(A=0;A<_paq.length;A++)if("setTrackerUrl"===_paq[A][0]||"setSiteId"===_paq[A][0])n(_paq[A]),delete _paq[A];for(A=0;A<_paq.length;A++)_paq[A]&&n(_paq[A]);_paq=new function(){return{push:n}};var fa={addPlugin:function(a,b){J[a]=b},getTracker:function(a,b){return new G(a,b)},getAsyncTracker:function(){return F}};"function"===typeof define&&define.amd&&
define(["piwik"],[],function(){return fa});return fa}());
"function"!==typeof piwik_log&&(piwik_log=function(a,r,l,n){function f(a){try{return eval("piwik_"+a)}catch(E){}}var m=PiwikNew.getTracker(l,r);m.setDocumentTitle(a);m.setCustomData(n);(a=f("tracker_pause"))&&m.setLinkTrackingTimer(a);(a=f("download_extensions"))&&m.setDownloadExtensions(a);(a=f("hosts_alias"))&&m.setDomains(a);(a=f("ignore_classes"))&&m.setIgnoreClasses(a);m.trackPageView();f("install_tracker")&&(piwik_track=function(a,f,p,v){m.setSiteId(f);m.setTrackerUrl(p);m.trackLink(a,v)})});
function FospAnalyticsNew(){var a=document,r=window,l=r.encodeURIComponent,n=r.decodeURIComponent;this.setCookie=function(c,b,e,f,h,k){var u;e&&(u=new Date,u.setTime(u.getTime()+1E3*e));a.cookie=c+"="+l(b)+(e?";expires="+u.toGMTString():"")+";path="+(f||"/")+(h?";domain="+h:"")+(k?";secure":"")};this.getCookie=function(c){return(cookieMatch=RegExp("(^|;)[ ]*"+c+"=([^;]*)").exec(a.cookie))?n(cookieMatch[2]):""};this.loadScript=function(a,b){var c=document.getElementsByTagName("head")[0],f=document.createElement("script");
f.type="text/javascript";f.src=a;f.async=!0;f.onreadystatechange=b;f.onload=b;c.appendChild(f)};this.getMeta=function(a){var b=document.getElementsByTagName("meta");if(0<b.length)for(var c=0;c<b.length;c++)if(null!=b[c].getAttribute("name")&&b[c].getAttribute("name").toLowerCase()==a.toLowerCase())return b[c].getAttribute("content");return!1};this.fosp_aid=this.getCookie("fosp_aid");this.fosp_loc=this.getCookie("fosp_loc");this.myvne=this.getCookie("myvne_user_id")||0;this.setStringForm=function(a,
																																																																																																																									 b,e){if(-1<a.indexOf("&"+b+"=")||0===a.indexOf(b+"=")){var c=a.indexOf("&"+b+"=");-1===c&&(c=a.indexOf(b+"="));var f=a.indexOf("&",c+1);return-1!==f?a.substr(0,c)+a.substr(f+(c?0:1))+"&"+b+"="+e:a.substr(0,c)+"&"+b+"="+e}return a+"&"+b+"="+e};this.getFospAll=function(a){var b=this.getCookie(a)||"",c=(new RegExp("(^|&)[ ]*"+a+"=([^&]*)","i")).exec(window.name);c=c&&2<c.length&&window.decodeURIComponent(c[2])||"";var f="";window.localStorage&&"function"==typeof window.localStorage.getItem&&(f=window.localStorage.getItem(a));
return b||f||c};this.writeCookieByDomain=function(a,b){var c=document.domain.split(".");if(1<c.length&&b)for(var f="."+c[c.length-1],h=c.length-2;0<=h;h--)if(f="."+c[h]+f,this.setCookie(a,b,31449600,"/",f),this.getCookie(a)==b){window.name=this.setStringForm(window.name,a,b);window.localStorage&&"function"==typeof window.localStorage.setItem&&window.localStorage.setItem(a,b);break}};var f="---",m=function(){r="";for(var a=0;16>a;a++)r+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));
return r=r+"."+Math.floor((new Date).getTime()/1E3)},w=function(a,b,e){return a.call.apply(a.bind,arguments)},E=function(a,b,e){if(!a)throw Error();if(2<arguments.length){var c=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,c);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},p=function(a,b,e){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?w:E;return p.apply(null,
arguments)};this.workerCookies=function(a){if(document.cookie!=f||2==a){f=document.cookie;var b=parseInt("0"+this.getCookie("myvne_user_id"))||0,c=this.getCookie("fosp_aid"),p=this.getCookie("orig_aid");a=this.getFospAll("fosp_aid")||"";var h=this.getFospAll("orig_aid")||"";if(1E4<b)c!=b&&(this.writeCookieByDomain("fosp_aid",b),c!=p&&(h=12<a.length?a:12<h.length?h:m(),this.writeCookieByDomain("orig_aid",h)));else if(""!=a&&a==parseInt("0"+a))this.writeCookieByDomain("fosp_aid",h);else if(c!=p||""==
c||""==p)b=12<a.length?a:12<h.length?h:m(),a!=b&&this.writeCookieByDomain("fosp_aid",b),h!=b&&this.writeCookieByDomain("orig_aid",b)}};var v=/(^|&)[ ]*fosp_aid=([^&]*)/.exec(window.name);v&&2<v.length&&window.decodeURIComponent(v[2]);window.setInterval(p(this.workerCookies,this),1E3);this.workerCookies(2);this.logData=function(a){try{for(var b="net com edu org gov biz info".split(" "),c=0,f=b.length;c<f;++c)b.push(b[c]+"\\.vn");b.push("vn");b.push("us");var h=RegExp("(\\.?[^.]+\\.("+b.join("|")+")$)"),
k=document.domain.match(h),p;null!==k?p=k[1]:(k=document.domain.match(/(\.?[^.]+\.?[^.]+$)/),null!==k&&(p=k[1]));"."==p[0]&&(p=p.substr(1));var m=(v=/(^|&)[ ]*fosp_aid=([^&]*)/.exec(window.name))?window.decodeURIComponent(v[2]):this.fosp_aid,l=this.getCookie("myvne_user_id")||m||this.fosp_aid;_paq.push(["setTrackerUrl","//la.vnecdn.net/get"]);_paq.push(["setSiteId",a]);_paq.push(["setFospId",l]);_paq.push(["setLocation",this.fosp_loc]);var r=this.getMeta("keywords"),n=this.getMeta("description"),
w=this.getMeta("tt_category_id");if(0!=w){_paq.push(["setCustomVariable","2","tt_category_id",w,"page"]);var t=this.getMeta("tt_article_id");0!=t&&_paq.push(["setCustomVariable","3","tt_article_id",t,"page"])}_paq.push(["setCustomVariable","4","fosp_aid",l,"visit"]);var y=this.getCookie("CPMS_LOG");null!==y&&0!=y&&_paq.push(["setCustomVariable","5","CPMS_LOG",y,"visit"]);_paq.push(["setCustomVariable","6","keyword",r+" "+n,"page"]);if("undefined"!==typeof Storage)try{var E=window.localStorage.eatv,
q=window.localStorage.fosp_session;_paq.push(["setCustomVariable","7","fosp_aid_bk",m,"visit"]);_paq.push(["setCustomVariable","8","eatv",E,"visit"]);_paq.push(["setCustomVariable","9","fosp_session",q,"visit"]);_paq.push(["setCustomVariable","10","fosp_gender",0,"visit"])}catch(T){}_paq.push(["setDocumentTitle",document.domain+"/"+document.title]);_paq.push(["setCookieDomain","*."+p]);PiwikNew.getAsyncTracker().trackPageView()}catch(T){}}}
var _pv=new FospAnalyticsNew,callback_ea=function(a){if(a.result){a.vid=(a.vid||"").substr(0,16);var r=[a.province,a.zone,a.country].join("-");if(r!=_pv.fosp_loc){var l=document.domain.split(".");if(1<l.length)for(var n="."+l[l.length-1],f=l.length-2;0<=f;f--)if(n="."+l[f]+n,_pv.setCookie("fosp_loc",r,63072E3,"/",n,0),_pv.getCookie("fosp_loc")==r){_pv.setCookie("fosp_country",a.country,63072E3,"/",n,0);_pv.setCookie("fosp_location",a.province,63072E3,"/",n,0);_pv.setCookie("fosp_location_zone",a.zone,
63072E3,"/",n,0);_pv.setCookie("fosp_isp",a.isp,63072E3,"/",n,0);_pv.setCookie("fosp_gender",a.fosp_gender,63072E3,"/",n,0);"undefined"!==typeof Storage&&(window.localStorage.news_aid=a.vid,window.localStorage.eatv=a.eatv,window.localStorage.fosp_session=a.fosp_session,window.localStorage.fosp_gender=a.fosp_gender);break}}}},_ea_loader_function=function(){_pv=_pv||new FospAnalyticsNew;try{_pv.logData(window._siteId)}catch(a){}};_ea_loader_function();
(function(){if("object"!==typeof a)var a=[];var r=2,l=document.createElement("script");l.src="//core.polyad.net/bad.js";l.async=!0;l.onload=l.onreadystatechange=function(){r=0};l.onerror=function(){r=1};document.getElementsByTagName("script")[0].parentNode.appendChild(l);var n=new function(){var f=document,m=window,l=m.encodeURIComponent,n=m.decodeURIComponent;this.a=function(a){return(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(f.cookie))?n(a[2]):""};this.debug=function(a){window.console&&window.console.log(a)};
this.b=function(a){var f=document.getElementsByTagName("meta");if(0<f.length)for(var c=0;c<f.length;c++)if(null!=f[c].getAttribute("name")&&f[c].getAttribute("name").toLowerCase()==a.toLowerCase())return f[c].getAttribute("content");return!1};this.c=function(a){var f=[],c;for(c in a)a.hasOwnProperty(c)&&("object"==typeof a[c]?f.push(this.c(a[c])):f.push(l(c)+"="+l(a[c])));return f.join("&")};this.f=function(){var f=r,l=this.a("fosp_location_zone"),c=this.a("fosp_country"),b=this.a("fosp_isp"),e=this.a("fosp_location"),
m=this.b("tt_site_id"),h=this.b("tt_page_type"),k=this.b("tt_category_id"),n=this.b("tt_article_id"),w=((this.a("fosp_aid")||(WNMatch=/(^|&)[ ]*fosp_aid=([^&]*)/.exec(window.name))&&window.decodeURIComponent(WNMatch[2]))+"").replace(/"|'/g,"").substr(0,40),E=this.a("fosp_gender"),G=this.a("fosp_ip"),M=parseInt(this.a("myvne_user_id"));a.push({idsite:m});a.push({type:h});a.push({fid:k});a.push({aid:n});a.push({fosp_aid:w});a.push({fosp_country:c});a.push({fosp_gender:E});a.push({fosp_ip:G});a.push({fosp_isp:b});
a.push({fosp_zone:l});a.push({fosp_location:e});a.push({adblock:f});a.push({myvne_user_id:M});a.push({referrer:document.referrer});a.push({r:Math.random()});f="//la2.vnecdn.net/get?"+this.c(a);document.createElement("img").src=f}};1<r?window.setTimeout(function(){1<r&&(r=0);n.f()},100):n.f()})();