Function.prototype.bind||(Function.prototype.bind=function(){var a=this,n=Array.prototype.slice.call(arguments),l=n.shift();return function(){return a.apply(l,n.concat(Array.prototype.slice.call(arguments)))}});
var isMobile={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},any:function(){return isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows()}},enDic={CLOSE_TEXT_LABEL:"Close Ad",
ERROR_MESSAGE_LABEL:"Video content error. Please try again by Ctrl + F5!",AD_MESSAGE:"Ad will show after",AD_LOADING:"Ad loading...",AD_SKIP:"Close Ad after",AD_DIMENSSION:"s",REPLAY_LABEL:"Replay",STOP_LABEL:"Stop",AUTO_NEXT_LABEL:"Next",SUGGESTION_LABEL:"Suggestion"},viDic={CLOSE_TEXT_LABEL:"B\u1ecf qua qu\u1ea3ng c\u00e1o",ERROR_MESSAGE_LABEL:"N\u1ed9i dung kh\u00f4ng th\u1ec3 xem l\u00fac n\u00e0y. Vui l\u00f2ng Ctrl + F5 \u0111\u1ec3 th\u1eed l\u1ea1i!",AD_MESSAGE:"Qu\u1ea3ng c\u00e1o s\u1ebd c\u00f3 th\u1ec3 hi\u1ec3n th\u1ecb sau",
AD_SKIP:"B\u1ecf qua qu\u1ea3ng c\u00e1o sau",AD_LOADING:"\u0110ang t\u1ea3i qu\u1ea3ng c\u00e1o...",AD_DIMENSSION:"gi\u00e2y",REPLAY_LABEL:"Xem l\u1ea1i",STOP_LABEL:"D\u1eebng",AUTO_NEXT_LABEL:"Ti\u1ebfp theo",SUGGESTION_LABEL:"C\u00f3 th\u1ec3 b\u1ea1n quan t\u00e2m"},selectDic="undefined"!=typeof SITE_ID&&1003888==SITE_ID||"undefined"!=typeof ZONE_ADS&&1==ZONE_ADS?enDic:viDic;
function AdObject(a,n,l,t,L){var u=a.id().replace("_html5_api",""),e=a.contentEl().children[0],I="";0==L&&(I=t);var y=this.moinitAd=this.moinitIMA=!1,w=!1,m=[],d=document.getElementById(n),k=document.getElementById(l),C,E,f,z,J="paused",D=null,x,r,p,P=!1;this.mainSource=a.src();this.moadDataXml="";var K=6,F=null,h,A=null,G=5,H=null,M=!1;this.moMainCurrentTime=0;var N="";this.playAd=function(){return w};this.loadAd=function(){return y};this.initAd=function(a){if(a)this.moinitAd=a;else return this.moinitAd};
this.pauseAd=function(){f&&f.pause()};this.initAdPlugin=function(a){if(a)this.moinitIMA=a;else return this.moinitIMA};this.mainCurrentTime=function(a){if("undefined"!==typeof a)this.moMainCurrentTime=a;else return this.moMainCurrentTime};this.moslotForCurrentTime=function(a){z=null;for(v in m)m[v].seen||m[v].time!=a||(z=m[v]);z&&Q(z)};this.moslotForType=function(a){for(v in m)if(!m[v].seen&&m[v].type==a)return(z=m[v])&&Q(z),m[v];return null};this.removeAdData=function(){clearInterval(A);clearTimeout(D);
clearTimeout(H);f&&f.destroy();d&&(d.innerHTML="",d.style.display="none");h&&a&&document.getElementById(a.id())&&(document.getElementById(a.id()).removeChild(h),h=null);k&&(k.innerHTML="",k.style.display="none",k.style.height="1px",k.style.width="1px");w=y=!1;moMainCurrentTime=0;a&&(mainSource=a.src());this.initIMA()};this.initIMA=function(){"undefined"!=typeof google&&d&&(d.style.display="none",google.ima.settings.setVpaidMode(google.ima.ImaSdkSettings.VpaidMode.ENABLED),C=new google.ima.AdDisplayContainer(d,
e),E=new google.ima.AdsLoader(C),f=null,E.addEventListener(google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,U,!1,E),E.addEventListener(google.ima.AdErrorEvent.Type.AD_ERROR,function(a){R(a)},!1));this.initAdPlugin(!0)};var U=function(a){var b=new google.ima.AdsRenderingSettings;b.restoreCustomPlaybackStateOnAdBreakComplete=!0;b.useStyledNonLinearAds=!0;f=a.getAdsManager(e,b);f.addEventListener(google.ima.AdErrorEvent.Type.AD_ERROR,R);f.addEventListener(google.ima.AdEvent.Type.CONTENT_PAUSETE_REQUESD,
V);f.addEventListener(google.ima.AdEvent.Type.CONTENT_RESUME_REQUESTED,W);f.addEventListener(google.ima.AdEvent.Type.ALL_ADS_COMPLETED,q);f.addEventListener(google.ima.AdEvent.Type.LOADED,q);f.addEventListener(google.ima.AdEvent.Type.STARTED,q);f.addEventListener(google.ima.AdEvent.Type.AD_PROGRESS,q);f.addEventListener(google.ima.AdEvent.Type.COMPLETE,q);f.addEventListener(google.ima.AdEvent.Type.FIRST_QUARTILE,q);f.addEventListener(google.ima.AdEvent.Type.MIDPOINT,q);f.addEventListener(google.ima.AdEvent.Type.THIRD_QUARTILE,
q);f.addEventListener(google.ima.AdEvent.Type.CLICK,q);f.addEventListener(google.ima.AdEvent.Type.SKIPPED,q);f.addEventListener(google.ima.AdEvent.Type.VOLUME_MUTED,q);f.addEventListener(google.ima.AdEvent.Type.VOLUME_CHANGED,q);f.addEventListener(google.ima.AdEvent.Type.RESUMED,q);f.addEventListener(google.ima.AdEvent.Type.IMPRESSION,q);f.addEventListener(google.ima.AdEvent.Type.LINEAR_CHANGED,q);f.addEventListener(google.ima.AdEvent.Type.PAUSED,q);f.addEventListener(google.ima.AdEvent.Type.USER_CLOSE,
q);try{f.init(e.offsetWidth,e.offsetHeight,google.ima.ViewMode.NORMAL),f.start()}catch(g){d.style.display="none"}}.bind(this);this.moinitAds2=function(b){if(window.adb||"undefined"==typeof google)return!1;C&&C.initialize();m=[];G=5;h=document.createElement("div");document.getElementById(a.id()).appendChild(h);h&&(h.className="ad_time_txt",h.innerHTML=selectDic.AD_MESSAGE+' <strong style="color:#fff; font-size: 13px;">'+G+"</strong> "+selectDic.AD_DIMENSSION);setTimeout(function(){h&&(h.className=
"ad_time_txt txt_fly_in")},100);clearInterval(F);F=setInterval(function(){if(a.paused())return!1;--G;h&&(h.innerHTML=selectDic.AD_MESSAGE+' <strong style="color:#fff; font-size: 13px;">'+G+"</strong> "+selectDic.AD_DIMENSSION);1==G&&(clearInterval(F),this.moslotForType("pre-roll")||(moadsShowing=!1,f&&f.destroy(),d.style.display="none",clearTimeout(void 0),h.className="ad_time_txt",setTimeout(function(){h&&document.getElementById(a.id())&&(document.getElementById(a.id()).removeChild(h),h=null)},1100),
moresumeMainContent(!1)))}.bind(this),1E3);try{var c=0,e=0,l=0;over=0;for(i in b.adlist)switch(b.adlist[i].type){case "preroll":var k=new moAdSlot("pre-roll-"+c,"pre-roll",0,"",b.adlist[i].duration,convertTimeFormat(b.adlist[i].skipOffset),"",b.adlist[i].tag,"",a.duration());c++;m.push(k);break;case "midroll":k=new moAdSlot("mid-roll-"+e,"mid-roll",b.adlist[i].offset,"",b.adlist[i].duration,convertTimeFormat(b.adlist[i].skipOffset),"",b.adlist[i].tag,"",a.duration());e++;m.push(k);break;case "postroll":k=
new moAdSlot("post-roll-"+l,"post-roll",a.duration(),"",b.adlist[i].duration,convertTimeFormat(b.adlist[i].skipOffset),"",b.adlist[i].tag,"",a.duration());l++;m.push(k);break;case "overlay":k=new moAdSlot("overlay"+over,"overlay",b.adlist[i].offset,"",convertTimeFormat(b.adlist[i].duration),convertTimeFormat(b.adlist[i].skipOffset),b.adlist[i].size,b.adlist[i].tag,b.adlist[i].script,a.duration()),over++,m.push(k)}console.log(m)}catch(B){console.log("LOG:ADS",B)}}.bind(this);this.moinitAds=function(b){if(window.adb||
"undefined"==typeof google)return!1;C&&C.initialize();m=[];try{var c=new XMLHttpRequest;c.onreadystatechange=function(f){if(4==c.readyState&&200==c.status&&(moadDataXml=c.responseXML,0<c.getResponseHeader("Content-Type").indexOf("xml")&&1==validateXML(moadDataXml))){try{var d=document.createAttribute("adtitle");d.value=moadDataXml.getElementsByTagName("AdTitle")[0].childNodes[0].nodeValue;e.setAttributeNode(d)}catch(T){console.log("cannot add attribute for video tag!!!")}try{var g=1==moadDataXml.getElementsByTagName("Configs").length?
parseAdsParameters(moadDataXml.getElementsByTagName("Configs")[0].childNodes[0].nodeValue):parseAdsParameters('{"'+moadDataXml.getElementsByTagName("Ad")[0].getAttribute("id")+'":{"type":"preroll","skipOffset":"00:00:06","duration":"00:00:30"}}'),h=0,k=0,l=0,n=0;Object.keys(g).forEach(function(b){for(var c=moadDataXml.getElementsByTagName("Ad"),e=0;e<c.length;e++)if(c[e].getAttribute("id")===b)switch(g[b].type){case "preroll":var d=new moAdSlot("pre-roll-"+h,"pre-roll",0,b,convertTimeFormat(g[b].duration),
convertTimeFormat(g[b].skipOffset),"","",void 0!=g[b].script?g[b].script:"",a.duration());h++;m.push(d);break;case "midroll":d=new moAdSlot("mid-roll-"+k,"mid-roll",convertTimeFormat(g[b].starttime),b,convertTimeFormat(g[b].duration),convertTimeFormat(g[b].skipOffset),"","",void 0!=g[b].script?g[b].script:"",a.duration());k++;m.push(d);break;case "postroll":d=new moAdSlot("post-roll-"+l,"post-roll",a.duration(),b,convertTimeFormat(g[b].duration),convertTimeFormat(g[b].skipOffset),"","",void 0!=g[b].script?
g[b].script:"",a.duration());l++;m.push(d);break;case "overlay":d=new moAdSlot("overlay"+n,"overlay",convertTimeFormat(g[b].starttime),b,convertTimeFormat(g[b].duration),convertTimeFormat(g[b].skipOffset),"","",void 0!=g[b].script?g[b].script:"",a.duration()),n++,m.push(d)}});this.moslotForType("pre-roll")}catch(T){try{errorTrackingUrl=b.getElementsByTagName("Error")[0].childNodes[0].nodeValue}catch(Y){errorTrackingUrl=""}}try{moadDataXml.getElementsByTagName("AdRequest")}catch(T){}}}.bind(this);
if(0<=b.indexOf("eclick.vn"))c.open("GET",decodeURI(b)+(0<decodeURI(b).indexOf("?")?"&dur=":"?dur=")+a.duration()+"&sw="+e.offsetWidth+"&sh="+e.offsetHeight+"&fosp_aid="+getCookie("fosp_aid")+"&retargeting_id="+("undefined"!=typeof ASPQ_gebMWv?ASPQ_gebMWv:"")+"&gwdadgroup="+("undefined"!=typeof gwdadgroup?gwdadgroup:"")+"&gwdblob="+("undefined"!=typeof gwdblob?gwdblob:"")+"&gwdadserver="+("undefined"!=typeof gwdadserver?gwdadserver:"")+"&gwd="+("undefined"!=typeof gwd?gwd:"")+"&pv="+(Math.random().toString(36)+
"00000000000000000").slice(2,12)+"&adb="+window.adb+(null!=e.getAttribute("data-ex")&&""!=e.getAttribute("data-ex")?"&"+e.getAttribute("data-ex"):""),!0);else{var f=window.location!=window.parent.location?document.referrer:document.location.href,d=decodeURI(b);d=d.replace("[timestamp]",(new Date).getTime());d=d.replace("[referrer_url]",encodeURI(f));try{b=window.location.href.split("/"),d=d.replace("[description_url]",encodeURI(b[0]+"//"+b[2]))}catch(S){console.log("cannot get href")}d+="&cust_params="+
encodeURIComponent("ap=0"+(null!=e.getAttribute("data-ex")&&""!=e.getAttribute("data-ex")?"&"+e.getAttribute("data-ex"):""));c.open("GET",d)}window.ASPQ_gebMWv=window.gwdadgroup=window.gwdblob=window.gwdadserver=window.gwd="";c.withCredentials=!1;c.send()}catch(S){console.log("error load ad data!"+S)}}.bind(this);var Q=function(b){M=!1;y=!0;clearInterval(A);clearTimeout(D);if(window.adb)return!1;b.seen=!0;if(""!=I)try{if("overlay"==b.type)if(""!=b.tag){var c=b.tag;if(0<=c.indexOf("eclick.vn"))c.open("GET",
decodeURI(g)+(0<decodeURI(g).indexOf("?")?"&dur=":"?dur=")+a.duration()+"&sw="+e.offsetWidth+"&sh="+e.offsetHeight+"&fosp_aid="+getCookie("fosp_aid")+"&retargeting_id="+("undefined"!=typeof ASPQ_gebMWv?ASPQ_gebMWv:"")+"&gwdadgroup="+("undefined"!=typeof gwdadgroup?gwdadgroup:"")+"&gwdblob="+("undefined"!=typeof gwdblob?gwdblob:"")+"&gwdadserver="+("undefined"!=typeof gwdadserver?gwdadserver:"")+"&gwd="+("undefined"!=typeof gwd?gwd:"")+"&pv="+(Math.random().toString(36)+"00000000000000000").slice(2,
12)+"&adb="+window.adb+(null!=e.getAttribute("data-ex")&&""!=e.getAttribute("data-ex")?"&"+e.getAttribute("data-ex"):""),!0);else{c=decodeURI(c);c=c.replace("[timestamp]",(new Date).getTime());try{var g=window.location.href.split("/");c=c.replace("[description_url]",encodeURI(g[0]+"//"+g[2]))}catch(B){console.log("cannot get href")}c=c.replace("[referrer_url]",encodeURI(window.location!=window.parent.location?document.referrer:document.location.href));c+="&cust_params="+encodeURIComponent("ap=0"+
(null!=e.getAttribute("data-ex")&&""!=e.getAttribute("data-ex")?"&"+e.getAttribute("data-ex"):""))}"undefined"!=typeof google&&O(c,!0);window.ASPQ_gebMWv=window.gwdadgroup=window.gwdblob=window.gwdadserver=window.gwd=""}else X(b);else{c=b.tag;if(0<=c.indexOf("eclick.vn"))c.open("GET",decodeURI(g)+(0<decodeURI(g).indexOf("?")?"&dur=":"?dur=")+a.duration()+"&sw="+e.offsetWidth+"&sh="+e.offsetHeight+"&fosp_aid="+getCookie("fosp_aid")+"&retargeting_id="+("undefined"!=typeof ASPQ_gebMWv?ASPQ_gebMWv:"")+
"&gwdadgroup="+("undefined"!=typeof gwdadgroup?gwdadgroup:"")+"&gwdblob="+("undefined"!=typeof gwdblob?gwdblob:"")+"&gwdadserver="+("undefined"!=typeof gwdadserver?gwdadserver:"")+"&gwd="+("undefined"!=typeof gwd?gwd:"")+"&pv="+(Math.random().toString(36)+"00000000000000000").slice(2,12)+"&adb="+window.adb+(null!=e.getAttribute("data-ex")&&""!=e.getAttribute("data-ex")?"&"+e.getAttribute("data-ex"):""),!0);else{c=decodeURI(c);c=c.replace("[timestamp]",(new Date).getTime());try{g=window.location.href.split("/"),
c=c.replace("[description_url]",encodeURI(g[0]+"//"+g[2]))}catch(B){console.log("cannot get href")}c=c.replace("[referrer_url]",encodeURI(window.location!=window.parent.location?document.referrer:document.location.href));try{g=window.location.href.split("/"),c=c.replace("[description_url]",encodeURI(g[0]+"//"+g[2]))}catch(B){console.log("cannot get href")}c+="&cust_params="+encodeURIComponent("ap=0"+(null!=e.getAttribute("data-ex")&&""!=e.getAttribute("data-ex")?"&"+e.getAttribute("data-ex"):"")+
"&aex=0&brs="+(ZONE_BRANDSAFE?ZONE_BRANDSAFE:""))}"undefined"!=typeof google&&O(c,!0);window.ASPQ_gebMWv=window.gwdadgroup=window.gwdblob=window.gwdadserver=window.gwd=""}}catch(B){console.log(B)}else{""!=b.script&&(c=document.createElement("script"),c.text=decodeURIComponent(b.script),document.head.appendChild(c).parentNode.removeChild(c));try{var d=moadDataXml.getElementsByTagName("Ad");for(c=0;c<d.length;c++)if(d[c].getAttribute("id")===b.id){var f=(new DOMParser).parseFromString('<VAST version="2.0"></VAST>',
"text/xml");f.getElementsByTagName("VAST")[0].appendChild(d[c]);g=(new XMLSerializer).serializeToString(f);"undefined"!=typeof google&&O(g,!1)}}catch(B){console.log("error load ad data!"+B)}}}.bind(this),O=function(b,c){clearInterval(A);N=a.poster();a.poster("");mainSource=a.src();moMainCurrentTime=a.currentTime();"post-roll"!=z.type&&"mid-roll"!=z.type||a.pause();d.style.backgroundColor="transparent";d.style.height="1px";d.style.width="1px";d.style.top=0;d.style.left=0;d.style.display="block";var g=
new google.ima.AdsRequest;c?g.adTagUrl=b:g.adsResponse=b;g.linearmoAdSlotWidth=e.offsetWidth;g.linearmoAdSlotHeight=e.offsetHeight;g.nonLinearmoAdSlotWidth=e.offsetWidth;g.nonLinearmoAdSlotHeight=e.offsetHeight;E.requestAds(g)}.bind(this),V=function(){moMainCurrentTime=a.currentTime();a.pause()}.bind(this),W=function(){this.moresumeMainContent(!0)}.bind(this),R=function(b){b=b.getError();console.log(b);f&&f.destroy();clearInterval(A);d.style.display="none";w=y=!1;clearTimeout(void 0);clearInterval(F);
h&&(h.className="ad_time_txt");setTimeout(function(){h&&document.getElementById(a.id())&&(document.getElementById(a.id()).removeChild(h),h=null)},1100);this.moresumeMainContent(400==b.getErrorCode()||400==b.getVastErrorCode()?!0:!1)}.bind(this),q=function(b){x=b.getAd();switch(b.type){case google.ima.AdEvent.Type.USER_CLOSE:this.moresumeMainContent(!0);break;case google.ima.AdEvent.Type.PAUSED:J="paused";try{playerStatusChange(u,"paused")}catch(c){console.log(c)}break;case google.ima.AdEvent.Type.RESUMED:J=
"playing";try{playerStatusChange(u,"playing")}catch(c){console.log(c)}break;case google.ima.AdEvent.Type.CLICK:"paused"==J?f.resume():"playing"==J&&f.pause();break;case google.ima.AdEvent.Type.LOADED:console.log("AD INFO: ",x);if("undefined"!=typeof window.track&&0<window.track.length)for(b=0;b<window.track.length;b++)window.track[b].mode="hidden";d.style.height="100%";d.style.width="100%";if(0<=x.getContentType().indexOf("audio")||0==e.offsetHeight||0<=x.getContentType().indexOf("video/3gpp"))return f.stop(),
!1;clearInterval(F);h&&(h.innerHTML=selectDic.AD_LOADING);if(x.isLinear()){isMobile.any()?(isMobile.Android()||document.getElementById(u).children[0].src==mainSource)&&a.pause():a.pause();for(v in m)!m[v].seen&&"overlay"==m[v].type&&a.currentTime()+15>m[v].time&&a.currentTime()+15<a.duration()&&(m[v].time=Math.floor(a.currentTime()+15));d.style.left="0";d.style.top="0";w=!0}else w=!1,d.style.top="-40px",clearTimeout(D),D=setTimeout(function(){f.stop()},1E4);break;case google.ima.AdEvent.Type.AD_PROGRESS:P||
5!=Math.round(b.getAdData().duration-f.getRemainingTime())||(P=!0,Video.trackingDataPlayer(a.id(),"videoAd5s",a.src(),"",((new Date).getTime()-a.rtv)/1E3),a.rtv=(new Date).getTime());document.getElementById(u+"_adProgess")&&(document.getElementById(u+"_adProgess").style.width=100*(b.getAdData().duration-f.getRemainingTime())/b.getAdData().duration+"%");break;case google.ima.AdEvent.Type.STARTED:Video.trackingDataPlayer(a.id(),"videoAdStart",a.src(),"0%",((new Date).getTime()-a.rtv)/1E3);a.rtv=(new Date).getTime();
if(x.isLinear()){try{a.player_.removeClass("vjs-controls-enabled"),a.player_.addClass("vjs-controls-disabled")}catch(c){console.log("cannot hide controls!!!")}a.pause();if(0<=x.getContentType().indexOf("video")||0<=x.getContentType().indexOf("application/x-mpeg")||0<=x.getContentType().indexOf("application/javascript"))d.style.display="block",r=document.createElement("div"),r.className="fp-ad-close-text",r.id=u+"_fpAdClose",r.style.fontSize=Math.round(5*e.offsetHeight)/100+"px",p=document.createElement("div"),
p.className="vjs-progress-holder vjs-slider vjs-slider-horizontal",p.id=u+"_adProgressBar",p.style.height="4px",p.style.backgroundColor="#acacac",p.style.display=0<=x.getContentType().indexOf("application/javascript")?"none":"block",p.style.position="absolute",p.style.bottom="0",p.style.width="100%",p.style.margin="0",p.style.padding="0",""!=d.innerHTML&&(d.appendChild(r),r&&(r.innerHTML=selectDic.AD_SKIP+" 6 "+selectDic.AD_DIMENSSION),d.appendChild(p),p&&(p.innerHTML='<div id="'+u+'_adProgess" class="ad-play-progress" style="width: 0%;height:100%;background-color:#ffb100;"></div>')),
h&&(h.className="ad_time_txt"),setTimeout(function(){h&&document.getElementById(a.id())&&(document.getElementById(a.id()).removeChild(h),h=null)},1100),clearInterval(A),K=6,A=setInterval(function(){--K;r&&(r.innerHTML=selectDic.AD_SKIP+" "+K+" "+selectDic.AD_DIMENSSION);if(0==K)return clearInterval(A),r&&(r.innerHTML=selectDic.CLOSE_TEXT_LABEL,r.addEventListener("click",function(){Video.trackingDataPlayer(a.id(),"videoAdSkip",a.src(),"",((new Date).getTime()-a.rtv)/1E3);a.rtv=(new Date).getTime();
moadsShowing=!1;f.stop();H=setTimeout(function(){try{this.moresumeMainContent(!0)}catch(c){console.log("cannot stop this ads!")}}.bind(this),1E3)}.bind(this),!1)),!1}.bind(this),1E3)}break;case google.ima.AdEvent.Type.COMPLETE:clearTimeout(H);Video.trackingDataPlayer(a.id(),"videoAdComplete",a.src(),"100%",((new Date).getTime()-a.rtv)/1E3);a.rtv=(new Date).getTime();this.moresumeMainContent(!0);break;case google.ima.AdEvent.Type.ALL_ADS_COMPLETED:clearTimeout(H),this.moresumeMainContent(!0)}}.bind(this),
X=function(b){b.script=b.script.replace(/div-gpt-ad-overlay/gi,a.id().replace("media-video-","").replace("_html5_api","")+"-div-gpt-ad-overlay");k.style.display="block";k.style.width=0!=b.width?b.width+"px":"480px";k.style.height=0!=b.height?b.height+"px":"70px";k.style.overflow="hidden";k.style.left=(k.parentNode.offsetWidth-(0!=b.width?b.width:480))/2+"px";k.style.top=k.parentNode.offsetHeight-(0!=b.height?b.height:70)-40+"px";k.innerHTML=decodeURIComponent(b.script);var c=document.createElement("div");
c.className="fp-ad-close-button";k.appendChild(c);c&&c.addEventListener("click",function(){clearTimeout(D);k.innerHTML="";k.style.display="none";k.style.height="1px";k.style.width="1px";w=y=!1},!1);D=setTimeout(function(){k.innerHTML="";k.style.display="none";w=y=!1},1E3*b.duration);b=k.getElementsByTagName("script");for(c=0;c<b.length;c++){var d=b[c],e=d.parentElement,f=document.createElement("script");if(""==d.getAttribute("async")||"true"==d.getAttribute("async"))f.async=!0;d.src&&(f.src=d.src);
d.text&&(f.text=d.text);e.insertBefore(f,d);e.removeChild(d)}}.bind(this);this.moresumeMainContent=function(b){if(M)return!1;M=!0;clearTimeout(H);h&&document.getElementById(a.id())&&(document.getElementById(a.id()).removeChild(h),h=null);d&&(d.style.display="none",d.style.height="1px",d.style.width="1px",r&&d.contains(r)&&(d.removeChild(r),r=null),p&&d.contains(p)&&(d.removeChild(p),p=null));w=y=!1;clearInterval(A);""!=N&&a.poster(N);a.ended()?Video.showEndVideo(a.id().replace("media-video-","").replace("_html5_api",
"")):a.play();"undefined"!=typeof window.track&&0<window.track.length&&(window.track[0].mode="showing");try{a.player_.removeClass("vjs-controls-disabled"),a.player_.addClass("vjs-controls-enabled")}catch(c){}};this.screenChange=function(){f&&f.resize(e.offsetWidth,e.offsetHeight,a.isFullscreen()?google.ima.ViewMode.FULLSCREEN:google.ima.ViewMode.NORMAL);document.getElementById(u+"_fpAdClose")&&(document.getElementById(u+"_fpAdClose").style.fontSize=Math.round(4*e.offsetHeight)/100+"px")}}
function parseAdsParameters(a){return!/[^,:{}\[\]0-9.\-+Eaeflnr-u \n\r\t]/.test(a.replace(/"(\\.|[^"\\])*"/g,""))&&eval("("+a+")")}function convertTimeFormat(a){return 3600*a.substr(0,1)+60*a.substr(3,2)+1*a.substr(6,2)}
function moAdSlot(a,n,l,t,L,u,e,I,y,w){this.name=a;this.type=n;this.tag=I;this.script=y;"number"===typeof l?this.time=l:"string"===typeof l&&0<=l.indexOf("%")?isNaN(w)?this.time=l:this.time=Math.floor(parseInt(l.substr(0,l.length-1))*w/100):this.time=convertTimeFormat(l);this.id=t;this.skip=0<parseInt(u)?parseInt(u):5;this.source="";this.duration=L;this.sourceType="";void 0!=e&&""!=e?(this.width=parseInt(e.substr(0,e.indexOf("x"))),this.height=parseInt(e.substr(e.indexOf("x")+1,e.length))):this.height=
this.width=0;this.seen=!1}function getCookie(a){a+="=";for(var n=document.cookie.split(";"),l=0;l<n.length;l++){for(var t=n[l];" "==t.charAt(0);)t=t.substring(1);if(0==t.indexOf(a))return t.substring(a.length,t.length)}return""}function setCookie(a,n,l){var t=new Date;t.setTime(t.getTime()+864E5*l);l="expires="+t.toUTCString();document.cookie=a+"="+n+";"+l+";domain="+document.domain+";path=/"}function getStorage(a){try{var n=localStorage.getItem(a)}catch(l){n=-1}return n}
function setStorage(a,n){try{localStorage.setItem(a,n);var l=1}catch(t){l=0}return l}function validateXML(a){if(window.ActiveXObject){var n=new ActiveXObject("Microsoft.XMLDOM");n.async=!1;n.loadXML(a);return 0!=n.parseError.errorCode?0:1}return document.implementation&&document.implementation.createDocument?(new DOMParser,0<a.getElementsByTagName("parsererror").length?0:1):0};