try{(function(d,u,k,n){function p(a){var b=a,c=((b=(new RegExp("(^|;)[ ]*"+b+"=([^;]*)")).exec(u.cookie))?v(b[2]):"")||"";b=(b=(new RegExp("(^|&)[ ]*"+a+"=([^&]*)","i")).exec(d.name))&&2<b.length&&d.decodeURIComponent(b[2])||"";var e="";q&&(e=d.localStorage.getItem(a));return b||c||e}k=d._logForm||(d._logForm=[]);if(k.push===Array.prototype.push){var q=0;try{"localStorage"in d&&d.localStorage&&"function"==typeof d.localStorage.getItem&&(q=1)}catch(a){q=0}var v=d.decodeURIComponent,w=function(a,b,
c){return a.call.apply(a.bind,arguments)},x=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,e);return a.apply(b,f)}}return function(){return a.apply(b,arguments)}},l=function(a,b,c){l=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?w:x;return l.apply(null,arguments)},y=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof
Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==
typeof a.call)return"object";return b},h=function(a){return"string"==typeof a},m=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},r=new function(){this.source_name="https://"+d.location.host;this.fosp_aid=p("fosp_aid");this.orig_aid=p("orig_aid");this.myvne_user_id=p("myvne_user_id");this.urlRequest="https://la2.vnecdn.net/formadp";this.timeoutUser=0;this.init=function(){if(d.postMessage&&d!==d.top){d.top.postMessage(JSON.stringify({id:"sync_user",
type:"tracking_banner"}),"*");var a=l(this.syncUserRely,this);d.addEventListener?d.addEventListener("message",a,!1):d.attachEvent&&d.attachEvent("onmessage",a)}this.timeoutUser=d.setTimeout(l(this.newUser,this),3E3)};this.setUser=function(a){if(""!=a){var b={};try{try{b=JSON.parse(a),b=b.data||{}}catch(c){b={}}}catch(c){}b&&(b.fosp_aid&&9<b.fosp_aid.length&&30>b.fosp_aid.length&&(this.fosp_aid=m(b.fosp_aid)),b.orig_aid&&15<b.orig_aid.length&&30>b.orig_aid.length&&(this.orig_aid=m(b.orig_aid)))}};
this.newUser=function(){if(!(this.fosp_aid&&this.orig_aid&&9<this.fosp_aid.length&&40>this.fosp_aid.length&&15<this.orig_aid.length&&40>this.orig_aid.length)){var a=l(this.setUser,this),b="https://adp.vnecdn.net/syncuser?"+["fosp_aid="+this.fosp_aid,"orig_aid="+this.orig_aid,"myvne_user_id="+this.myvne_user_id].join("&");this.sendRequest(b,"GET",{},{},a)}};this.syncUserRely=function(a){if(""!=a.data)try{var b=JSON.parse(a.data);if(b.id&&"sync_user_reply"==b.id&&b.fosp_aid&&b.orig_aid){this.timeoutUser&&
(d.clearTimeout(this.timeoutUser),this.timeoutUser=0);var c=b.fosp_aid||"",e=b.orig_aid||"",f=b.myvne_user_id||0;1E9<f&&3E9>f?this.myvne_user_id=this.fosp_aid=f:15<c.length&&40>c.length&&(this.fosp_aid=m(c));15<e.length&&40>e.length&&(this.orig_aid=m(e));""!=a.origin&&(this.source_name=m(a.origin))}}catch(g){}};this.sendRequest=function(a,b,c,e,f){4===arguments.length&&(f=e,e={});var g=new XMLHttpRequest;g.onerror=f;g.onreadystatechange=function(){if(4===g.readyState)return f(null,g)};for(var t in e)g.setRequestHeader(t,
e[t]);"POST"==b?(g.open("POST",a,!0),g.send(JSON.stringify(c))):(g.open("GET",a,!0),g.send())};this.tracking=function(a,b){b="function"==y(b)?b:function(){};a.campaign_name&&h(a.campaign_name)&&""!=a.campaign_name||console&&console.log("form tracking invalid data campaign_name",a);(!a.engagement_type||"number"!=typeof a.engagement_type||1>a.engagement_type)&&console&&console.log("form tracking invalid data evt_type",a);var c={fosp_aid:""+this.fosp_aid,orig_aid:""+this.orig_aid,myvne_user_id:""+this.myvne_user_id,
source_type:a.source_type&&"external"==a.source_type?2:1,source_name:""+this.source_name,campaign_name:""+a.campaign_name,engagement_type:""+a.engagement_type,evt_info:{}};a.index_brand&&h(a.index_brand)&&""!=a.index_brand&&(c.index_brand=a.index_brand);a.index_industrial&&h(a.index_industrial)&&""!=a.index_industrial&&(c.index_industrial=a.index_industrial);a.index_category&&h(a.index_category)&&""!=a.index_category&&(c.index_category=a.index_category);a.index_topic&&h(a.index_topic)&&""!=a.index_topic&&
(c.index_topic=a.index_topic);a.name&&h(a.name)&&""!=a.name&&(c.evt_info.name=a.name);a.email&&""!=a.email&&/\S+@\S+\.\S+/.test(a.email)&&(c.evt_info.email=a.email);a.age&&h(a.age)&&""!=a.age&&(c.evt_info.age=a.age);a.phone&&h(a.phone)&&""!=a.phone&&(c.evt_info.phone=a.phone);a.gender&&"number"==typeof a.gende&&0<a.gender&&3>a.gender&&(c.evt_info.gender=""+a.gender);this.sendRequest(this.urlRequest,"POST",c,{},b)}};r.init();if(k.push===Array.prototype.push){n=0;for(var z=k.length;n<z;++n)r.tracking(k[n]);
k.push=function(a){r.tracking(a)}}}})(window,document,location,history)}catch(d){console.log("error:",d)};