(function(q){function ra(a){var b=function(a,b){return a<<b|a>>>32-b},d=function(a){var b="",c,d;for(c=7;0<=c;c--)d=a>>>4*c&15,b+=d.toString(16);return b},c,k,g=[],h=1732584193,P=4023233417,r=2562383102,w=271733878,f=3285377520,e,n,s,m,v,y=[];a=unescape(q.encodeURIComponent(a));e=a.length;for(c=0;c<e-3;c+=4)k=a.charCodeAt(c)<<24|a.charCodeAt(c+1)<<16|a.charCodeAt(c+2)<<8|a.charCodeAt(c+3),y.push(k);switch(e&3){case 0:c=2147483648;break;case 1:c=a.charCodeAt(e-1)<<24|8388608;break;case 2:c=a.charCodeAt(e-
2)<<24|a.charCodeAt(e-1)<<16|32768;break;case 3:c=a.charCodeAt(e-3)<<24|a.charCodeAt(e-2)<<16|a.charCodeAt(e-1)<<8|128}for(y.push(c);14!==(y.length&15);)y.push(0);y.push(e>>>29);y.push(e<<3&4294967295);for(a=0;a<y.length;a+=16){for(c=0;16>c;c++)g[c]=y[a+c];for(c=16;79>=c;c++)g[c]=b(g[c-3]^g[c-8]^g[c-14]^g[c-16],1);k=h;e=P;n=r;s=w;m=f;for(c=0;19>=c;c++)v=b(k,5)+(e&n|~e&s)+m+g[c]+1518500249&4294967295,m=s,s=n,n=b(e,30),e=k,k=v;for(c=20;39>=c;c++)v=b(k,5)+(e^n^s)+m+g[c]+1859775393&4294967295,m=s,s=n,
n=b(e,30),e=k,k=v;for(c=40;59>=c;c++)v=b(k,5)+(e&n|e&s|n&s)+m+g[c]+2400959708&4294967295,m=s,s=n,n=b(e,30),e=k,k=v;for(c=60;79>=c;c++)v=b(k,5)+(e^n^s)+m+g[c]+3395469782&4294967295,m=s,s=n,n=b(e,30),e=k,k=v;h=h+k&4294967295;P=P+e&4294967295;r=r+n&4294967295;w=w+s&4294967295;f=f+m&4294967295}v=d(h)+d(P)+d(r)+d(w)+d(f);return v.toLowerCase()}function $(a,b){var d=new Image(1,1);if(b){var c=function(a){b(a);Q(d,"load",c);Q(d,"error",c)};K(d,"load",c);K(d,"error",c)}d.src=a}if(!q.eClick){Date.now=Date.now||
function(){return+new Date};q.JSON||(q.JSON={parse:function(a){return eval("("+a+")")},stringify:function(){var a=Object.prototype.toString,b=Array.isArray||function(b){return"[object Array]"===a.call(b)},d={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},c=function(a){return d[a]||"\\u"+(a.charCodeAt(0)+65536).toString(16).substr(1)},k=/[\\"\u0000-\u001F\u2028\u2029]/g;return function h(d){if(null==d)return"null";if("number"===typeof d)return isFinite(d)?d.toString():
"null";if("boolean"===typeof d)return d.toString();if("object"===typeof d){if("function"===typeof d.toJSON)return h(d.toJSON());if(b(d)){for(var r="[",f=0;f<d.length;f++)r+=(f?", ":"")+h(d[f]);return r+"]"}if("[object Object]"===a.call(d)){r=[];for(f in d)d.hasOwnProperty(f)&&r.push(h(f)+": "+h(d[f]));return"{"+r.join(", ")+"}"}}return'"'+d.toString().replace(k,c)+'"'}}()});var L=Array.prototype.forEach,R=Array.prototype.map,f={toArray:function(a){for(var b=[],d=0;d<a.length;++d)b[d]=a[d];return b},
forEach:function(a,b,d){if(L&&a.forEach===L)a.forEach(b);else for(var c=0,k=a.length;c<k&&!1!==b.call(d,a[c],c,a);++c);},map:function(a,b,d){var c=[];if(null==a)return c;if(R&&a.map===R)return a.map(b,d);f.forEach(a,function(a,g,h){c[c.length]=b.call(d,a,g,h)});return c},find:function(){},extend:function(a){f.forEach([].slice.call(arguments,1),function(b){if(b)for(var d in b)a[d]=b[d]});return a},isArray:Array.isArray||function(a){return"[object Array]"=={}.toString.call(a)},debounce:function(a,b,
d){var c,k;return function(){var g=this,h=arguments,f=d&&!c;clearTimeout(c);c=setTimeout(function(){c=null;d||(k=a.apply(g,h))},b);f&&(k=a.apply(g,h));return k}},tokenize:function(a,b,d){!b&&(b=",");!d&&(d=":");var c={};a=a.split(b);f.forEach(a,function(a){var b=a.split(d);a=b[0];b=b[1];a&&b&&(c[a]=b)});return c}},G;a:{var H=this.navigator;if(H&&(H=H.userAgent)){G=H;break a}G=""}var m=function(a){return-1!=G.toLowerCase().indexOf(a.toLowerCase())};m("Trident")||m("MSIE");m("Edge");!m("Gecko")||m("WebKit")&&
!m("Edge")||m("Trident")||m("MSIE")||m("Edge");m("WebKit")&&m("Edge");m("Macintosh");var ia=function(){return m("iPad")||m("Android")&&!m("Mobile")||m("Silk")},ja=function(){return/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/i.test(G)};(function(){function a(a){var b=document.createElement("script"),c=!1;b.src=a;b.async=!0;b.onload=b.onreadystatechange=function(){c||this.readyState&&
"loaded"!==this.readyState&&"complete"!==this.readyState||(c=!0,b.onload=b.onreadystatechange=null,b&&b.parentNode&&b.parentNode.removeChild(b))};d||(d=document.getElementsByTagName("head")[0]);d.appendChild(b)}var b=0,d,c,k,g=this,h={};return{get:function(d,f,m,q){c=-1===(d||"").indexOf("?")?"?":"&";f=f||{};for(k in f)f.hasOwnProperty(k)&&(c+=encodeURIComponent(k)+"="+encodeURIComponent(f[k])+"&");var e="json"+ ++b;g[e]=function(a){try{m(a),g[e]=function(){}}catch(b){g[e]=function(){}}};a(d+c+(q||
h.callbackName||"callback")+"="+e);return e},script:a,init:function(a){h=a}}})();(function(a,b,d){var c=function(a,b,d){return 1===arguments.length?c.get(a):c.set(a,b,d)};c.get=function(b){a.cookie!==c._cacheString&&c._populateCache();return c._cache[b]||""};c.defaults={path:"/"};c.set=function(b,g,h){h={path:h&&h.path||c.defaults.path,domain:h&&h.domain||c.defaults.domain,expires:h&&h.expires||c.defaults.expires,secure:h&&h.secure!==d?h.secure:c.defaults.secure};g===d&&(h.expires=-1);switch(typeof h.expires){case "number":h.expires=
new Date((new Date).getTime()+1E3*h.expires);break;case "string":h.expires=new Date(h.expires)}b=encodeURIComponent(b)+"="+(g+"").replace(/[^!#-+\--:<-[\]-~]/g,encodeURIComponent);b+=h.path?";path="+h.path:"";b+=h.domain?";domain="+h.domain:"";b+=h.expires?";expires="+h.expires.toGMTString():"";b+=h.secure?";secure":"";a.cookie=b;return c};c.expire=function(b,a){return c.set(b,d,a)};c._populateCache=function(){c._cache={};c._cacheString=a.cookie;for(var b=c._cacheString.split("; "),g=0;g<b.length;g++){var h=
b[g].indexOf("=");try{var f=decodeURIComponent(b[g].substr(0,h)),m=decodeURIComponent(b[g].substr(h+1))}catch(q){continue}c._cache[f]===d&&(c._cache[f]=m)}};c.enabled=function(){var b="1"===c.set("cookies.js","1").get("cookies.js");c.expire("cookies.js");return b}();return b.cookies=c})(document,f);(function(a){a=a||document.domain;a=a.replace(/^\s+/,"");a=a.replace(/\s+$/,"");a=a.replace(/\\/g,"/");a=a.replace(/^http\:\/\/|^https\:\/\/|^ftp\:\/\//i,"");a=a.replace(/^www\./i,"");var b=[".",a].join("");
a=a.split(".");for(var d="",c=[],k=[],g=1;g<=a.length;g++)c.push([".",a[a.length-g].replace(/[^a-zA-Z0-9]/g,"")].join(""));for(a=c.length;0<a;a--)d=c[c.length-a]+d,k.push(d);for(d=0;d<k.length;d++)try{if(!f.cookies)return;var h="1"===f.cookies.set("isCookieDomain","1",{domain:k[d]}).get("isCookieDomain");f.cookies.expire("isCookieDomain",{domain:k[d]});if(h)return k[d]}catch(m){}return b})();Function.prototype.bind||(Function.prototype.bind=function(){var a=this,b=Array.prototype.slice.call(arguments),
d=b.shift();return function(){return a.apply(d,b.concat(Array.prototype.slice.call(arguments)))}});document.getElementsByClassName||(document.getElementsByClassName=function(a){var b=document,d,c=[];if(b.querySelectorAll)return b.querySelectorAll("."+a);if(b.evaluate)for(b=b.evaluate(".//*[contains(concat(' ', @class, ' '), ' "+a+" ')]",b,null,0,null);d=b.iterateNext();)c.push(d);else for(b=b.getElementsByTagName("*"),a=new RegExp("(^|\\s)"+a+"(\\s|$)"),d=0;d<b.length;d++)a.test(b[d].className)&&
c.push(b[d]);return c});var M=function(a,b){for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.call(null,a[d],d,a)},S=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==
d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},T=function(a){return"string"==typeof a},sa=function(a){for(var b in a)return!1;return!0},K=function(a,b,d,c){return a.addEventListener?(a.addEventListener(b,d,c||!1),!0):a.attachEvent?(a.attachEvent("on"+b,d),!0):!1},Q=function(a,b,d,c){return a.removeEventListener?(a.removeEventListener(b,
d,c||!1),!0):a.detachEvent?(a.detachEvent("on"+b,d),!0):!1},U=function(a){return"function"==typeof encodeURIComponent?encodeURIComponent(a):escape(a)},B=function(a,b,d){d=d||("https:"==document.location.protocol?"https":"http");return[d,"://",a,b].join("")},ta=function(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else{if(navigator.userAgent&&0<=navigator.userAgent.indexOf("Windows CE")){for(var a=
3,b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1)),a++}catch(d){b=null}return a.toString()}if(-1!=navigator.userAgent.toLowerCase().indexOf("msie")&&!q.opera){b=null;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(c){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a=6,b.Ma="always"}catch(f){if(6==a)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(g){}}if(b)return a=b.GetVariable("$version").split(" ")[1],a.replace(/,/g,
".")}}return"0"},aa=function(){var a,b,d=1,c,f=this;return{postMessage:function(b,a,c){a&&(c=c||f.parent,f.postMessage?c.postMessage(b,a.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):a&&(c.location="#"+ +new Date+d++ +"&"+b))},receiveMessage:function(d,h){if(f.postMessage)if(c=function(b){d(b)},f.addEventListener)f[d?"addEventListener":"removeEventListener"]("message",c,!1);else f[d?"attachEvent":"detachEvent"]("onmessage",c);else a&&clearInterval(a),a=null,d&&(a=setInterval(function(){var a=document.location.hash,
c=/^#?\d+&/;a!==b&&c.test(a)&&(b=a,d({data:a.replace(c,"")}))},1E3))}}}();(function(){function a(a){var c=b.location.hash,t="object"==S(a.upf)&&a.upf.profile&&a.upf.profile||null,d={error:0,profile:{fosp_code:t&&t.fosp_code?t.fosp_code:"undefined"!=typeof a.upf?a.upf:"",myvne_id:f.cookies("myvne_user_id")?f.cookies("myvne_user_id"):"undefined"!=typeof q.vne_myvne_id?q.vne_myvne_id:t&&t.myvne_id?t.myvne_id:""}};M(H,function(a){if(c&&c.indexOf&&-1!=c.indexOf(a)){var b=c.match(new RegExp(a+"=([^&]*)"));
"focode"==a&&(a="fosp_code");d.profile[a]=b?b[1]:""}});return d}var b=q,d=document,c=b.location,k=navigator;b.timerPageview=b.timerPageview||null;var g=/(^|&)[ ]*fosp_aid=([^&]*)/.exec(b.name),g=g&&2<g.length&&b.decodeURIComponent(g[2])||f.cookies("fosp_aid")||!!b.localStorage&&b.localStorage.news_aid,h=function(){var a=1E3*Date.now()+~~(1E3*Math.random());return ra(a+"").substring(0,24)}(),m="undefined"!=typeof ZONE_ADS&&1==ZONE_ADS?"scdn.eclick.vn":"s.eclick.vn",r=function(a,c){c=c.replace(/\"/gi,
"");var t=d.domain.split(".");if(1<t.length&&c)for(var l="."+t[t.length-1],E=t.length-2;0<=E&&(l="."+t[E]+l,f.cookies(a,c,{expires:31536E3,domain:l,path:"/"}),f.cookies(a)!=c);E--);t=b;l=b.name;E=c;if(-1<l.indexOf("&"+a+"=")||0===l.indexOf(a+"=")){var I=l.indexOf("&"+a+"="),e;-1===I&&(I=l.indexOf(a+"="));e=l.indexOf("&",I+1);l=-1!==e?l.substr(0,I)+l.substr(e+(I?0:1))+"&"+a+"="+E:l.substr(0,I)+"&"+a+"="+E}else l=l+"&"+a+"="+E;t.name=l},w=function(){for(var a="",b=0;16>b;b++)a+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*
Math.random()));return a=a+"."+Math.floor((new Date).getTime()/1E3)};if(!g||"undefined"==g){var g=w(),A=f.cookies("myvne_user_id")||0,e=f.cookies("orig_aid")||"";1E6>A&&e!=g&&(r("fosp_aid",g),r("orig_aid",g))}var e=f.cookies("fosp_aid")||"",n=f.cookies("orig_aid")||"",A=f.cookies("myvne_user_id")||0,n=T(n)&&15<n.length&&40>n.length?n:w(),e=T(e)&&9<e.length&&40>e.length?e:w();if(A)A!=e&&(n&&""!=n||!isNaN(e)||(n=e),e=A);else if(""!=n&&n!=e&&isNaN(n)){if(9>e.length||32<e.length)e=n}else n=e;"undefined"==
e&&(e=w());if(!b.adsbyeclick||!b.adsbyeclick.loaded){var g=f.cookies("fosp_location_zone")||"0",s="undefined"!=typeof ZONE_ADS&&1==ZONE_ADS;q.fosp_location_zone=g;var G=(new Date).getTime(),v=/(^| )adsbyeclick($| )/,y={flash:"",java:"",html5:""},H={ezid:"eclick_review_ad_zone",ebid:"eclick_review_ad_banner",code:"focode"},Z={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},O={"'":"\\'"},z=function(a){z[" "](a);return a};z[" "]=function(){};
var V=function(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{z(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(d){return!1}},ba=null,Q=document,K=function(){if(!ba){for(var a=q,b=a,c=0;a&&a!=a.parent;)if(a=a.parent,c++,V(a))b=a;else break;ba=b}return ba},L=!!b.eclick_async_ad,D=L&&q.parent||q,W=function(a){try{return!!a&&null!=a.location.href&&K(a,"foo")}catch(b){return!1}},F=null,X;if(!F)a:{for(var g=[b.top],w=[],J,R=0;J=g[R++];)try{if(!W(J)||w.push(J),J.frames)for(var u=J.frames.length,
ca=0;ca<u&&1024>g.length;++ca)g.push(J.frames[ca])}catch(Ha){}for(u=0;u<w.length;u++)try{if(X=w[u].frames.eclick_sf){F=X;break a}}catch(Ia){}F=null}if(F)aa.postMessage(JSON.stringify({cb:["ufa",e,n,A].join(":"),unique:320771303}),"*",F);else{X=B("g.eclick.vn","/delivery/eclookup.html?"+["fosp_aid="+e,"orig_aid="+n,"myvne_user_id="+A].join("&"),"");u=document.createElement("iframe");u.src=X;u.id="eclick_sf";u.name="eclick_sf";u.width=0;u.height=0;u.style.display="none";0<document.getElementsByTagName("body").length&&
document.getElementsByTagName("body")[0].appendChild(u);u.onload=function(){aa.postMessage(JSON.stringify({cb:["ufa",e,n,A].join(":"),unique:320771303}),"*",F)};try{F=u.contentWindow}catch(Ja){}}var x=function(){B("t.eclick.vn","/getid?nid=fosp_aid");var a={orig_aid:n,myvne_user_id:A,fosp_aid:e,fosp_gender:f.cookies("fosp_gender").toString()||"",zone:f.cookies("fosp_location_zone")||"",province:f.cookies("fosp_location")||"",isp:f.cookies("fosp_isp")||"",country:f.cookies("fosp_country")||"",ip:f.cookies("fosp_ip")||
""};if(a.fosp_aid)return a}(),da=function(a,b,c){"undefined"==typeof c&&(c=!0);var d=[],e=[],f,g="",k="",m="";f=c?"url fosp_gender ts lz lc lp fosp_aid":"eclick_url fosp_gender eclick_start_time loc_zone loc_country loc_province fosp_aid";f=f.split(" ");M(a,function(a,b){for(var c=0;c<f.length;c++)if(b==f[c]){if("undefined"==a||null==a)a="";b==f[0]&&(b="origin");b==f[1]&&(b="gender");b==f[2]&&(b="ts");b==f[3]&&(b="lz",k=a);b==f[4]&&(b="lc",g=a);b==f[5]&&(b="lp",m=a);d.push(b+"="+a)}});var n;n=""!=
m||""!=k||""!=g?[m,"-",k,"-",g].join(""):"";d.push("loc="+n);d.push("ev=130920&v=4");a=a.eclick_device||"1";ja()&&(a="2",ia()&&(a="3"));d.push("device="+a);if(c){for(c=0;c<C.length;c++)C[c]&&e.push(C[c]);d.push("pv="+h+"+"+e.join("+"))}else d.push("pv="+h);return b+d.join("&")},ea=["eclick_update_data","eclick_update_imp_state","erta","ufa"],C=[],ka=0,fa=[],ua=[],va=function(a){for(var c=0;c<fa.length;c++)if(fa[c]==a.id)return;C.push(a.bc2);fa.push(a.id);var c=C.length,d;ka==b.eclick_unique_id&&c==
b.eclick_unique_id&&"true"!==b.pv_sent&&(d=da(a,B("t.eclick.vn","/pageview?"))+"&out=0",C=[],b.pv_sent="true",$(d,function(){b.timerPageview&&clearTimeout(b.timerPageview);b.timerPageview=null}));b.timerPageview=setTimeout(function(){0<C.length&&(d=da(a,B("t.eclick.vn","/pageview?"))+"&out=1",C=[],b.pv_sent="true",$(d,function(){b.timerPageview=null;C=[]}))},1E3)},wa=function(a){ua.push(a.id);a.url&&$(a.url,function(){})},Y=[];try{var N=b.localStorage.getItem("crtg");N&&(N=N.split(","),N.pop(),Y=
Y.concat(N));b.localStorage.getItem("abdtg")}catch(Ka){}aa.receiveMessage(function(a){var b,c="";try{b=JSON.parse(a.data)}catch(d){b={}}b&&b.type&&(c=b.type);c==ea[0]&&(ka++,va(b));c==ea[1]&&wa(b);c==ea[3]&&""!==b.values&&(a=b.values.split(","),1E5>(f.cookies("myvne_user_id")||0)&&1<a.length&&(r("fosp_aid",a[0]),r("orig_aid",a[1])))});var D=function(){if(L&&!W(D)){for(var a="."+Q.domain;2<a.split(".").length&&!W(D);)d.domain=a=a.substr(a.indexOf(".")+1),D=q.parent;W(D)||(D=q)}return D}(),xa=q.parent||
q,la=function(){for(var a=b,c=a;a&&a!=a.parent;)if(a=a.parent,V(a))c=a;else break;return xa=c}(),ya=function(){var a=k.userAgent.toLowerCase();return/IEMobile/i.test(k.userAgent)?"3":-1<a.indexOf("android")?"2":/iPad|iPhone|iPod/.test(k.platform)?"1":""},ga=function(){try{return b.self!==b.top}catch(a){return!0}},z=function(a){z[" "](a);return a};z[" "]=function(){};var K=function(a,b){try{return z(a[b]),!0}catch(c){}return!1},V=function(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{z(a.foo);
b=!0;break a}catch(c){}b=!1}return b}catch(d){return!1}},ma=function(a,b){if(!(2>arguments.length))for(var c=1,d=arguments.length;c<d;++c)a.push(arguments[c])},za=function(a,c,d){return function(){try{var d=b.document.getElementById(a).contentWindow;if(V(d)){var t=b.document.getElementById(a).contentWindow,f=t.document;f.body&&f.body.firstChild||(f.open(),f.write(c))}else{var e=b.document.getElementById(a).contentWindow,g;c=String(c);if(c.quote)g=c.quote();else{d=['"'];for(t=0;t<c.length;t++){var h=
c.charAt(t),k=h.charCodeAt(0),f=t+1,m;if(!(m=Z[h])){var n;if(31<k&&127>k)n=h;else{var p=h;if(p in O)n=O[p];else if(p in Z)n=O[p]=Z[p];else{var q=p,s=p.charCodeAt(0);if(31<s&&127>s)q=p;else{if(256>s){if(q="\\x",16>s||256<s)q+="0"}else q="\\u",4096>s&&(q+="0");q+=s.toString(16).toUpperCase()}n=O[p]=q}}m=n}d[f]=m}d.push('"');g=d.join("")}e.location.replace("javascript:"+g)}}catch(La){}}},Aa=function(){var a=0,c=b.setInterval(function(){a++;try{for(var t=d.getElementsByClassName("ad_wrapper_protection"),
l=0,f=t.length,e=t[l];l<f;e=t[++l])e&&0==e.getElementsByClassName("ad_frame_protection").length&&e.parentNode.removeChild(e);t=d.getElementsByClassName("oex-zone");l=0;f=t.length;for(e=t[l];l<f;e=t[++l])e.parentNode.removeChild(e)}catch(g){}9<a&&b.clearInterval(c)},1500)},Ba=function(a,c,d){c=z("script");var l={};l.width='"'+a.eclick_ad_width+'"';l.height='"'+a.eclick_ad_height+'"';l.frameborder='"0"';l.marginwidth='"0"';l.marginheight='"0"';l.vspace='"0"';l.hspace='"0"';l.allowtransparency='"true"';
l.scrolling='"no"';l.allowfullscreen='"true"';d(l,a);T(a.request_native)&&a.request_native==a.eclick_zone?a.html_template=U(a.html_template):T(a.request_native)&&delete a.request_native;var f;d=[];for(f in a)d.push(f+"="+("number"==typeof a[f]?a[f]:"string"==typeof a[f]?'"'+a[f]+'"':'""'));d.push("");f=d.join(";");d=z("script");d=["<",d,' src="',B(m,"/delivery/asset/320771303/ads_impl.js",""),'"></',d,">"].join("");var l="",l=B(m,"/delivery/asset/320771303/eclick.css",""),e=["<link "];e.push("rel=",
'"stylesheet" ');e.push("type=",'"text/css" ');e.push("href=",'"'+l+'" >');l=e.join("");c=["<!doctype html><html><head><meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=yes'>",l,"</head><body marginwidth='0' marginheight='0' leftmargin='0' topmargin='0'><",c,">eclick_unique_id=",b.eclick_unique_id,";"+f,"</",c,">",d,"</body></html>"].join("");za(a.eclick_frameId,c,!0)()},Ca=function(a,c){a.eclick_ip_client="";a.eclick_zone_ads=s?"qt":"tn";Ba(a,c,function(a,d){for(var f=
a.id,e=0;!f||b.document.getElementById(f);)f="eclick_ads_frame"+e++;a.id=d.eclick_frameId=f;a.name=f;a.className="ad_frame_protection";a.ad_oninit='"'+(d.eclick_ad_oninit?d.eclick_ad_oninit:"")+'"';a.ad_slider='"'+(d.eclick_ad_slider?d.eclick_ad_slider:"")+'"';var g,f=Number(d.eclick_ad_width),e=Number(d.eclick_ad_height),h=["<iframe"];for(g in a)a.hasOwnProperty(g)&&"className"!=g?ma(h,g+"="+a[g]):ma(h,"class="+a[g]);h.push('style="position:absolute;left:0;top:0;"');h.push("></iframe>");g=['<ins id="',
a.id+"_ins",'" style="',"display:"+('"2"'==a.ad_oninit?"none":"block")+";border:none;height:"+(2>e?"auto":e+"px")+";margin:0 auto;padding:0;position:relative;visibility:visible;width:"+(2>f?"100%":f+"px")+";background-color:transparent;",'"><div id="',a.id,'_div"><div id="',a.id,'_wrap" class="ad_wrapper_protection">',h.join(" "),"</div></div></ins>"].join("");c.innerHTML=g;return a.id})},na=function(a){for(var b=document.getElementsByTagName("ins"),c=0,d=b[c];c<b.length;d=b[++c])if(ha(d)&&(!a||d.id==
a))return d;return null},ha=function(a){return v.test(a.className)&&"done"!=a.getAttribute("data-adsbyeclick")},p={aa:"eclick_async_ad",st:"eclick_start_time",vs:"eclick_version",pv:"eclick_pv",rf:"eclick_ref",uv:"eclick_unique_version",dv:"eclick_device",ul:"eclick_url",ah:"eclick_ad_host",zn:"eclick_zone",ev:"eclick_video",eh:"eclick_hash",vi:"fosp_aid",oi:"orig_aid",mi:"myvne_user_id",gd:"fosp_gender",lc:"loc_country",lz:"loc_zone",lp:"loc_province",lis:"loc_isp",li:"loc_ip"},oa={myvne_user_id:"myvne_user_id",
orig_aid:"orig_aid",fosp_aid:"fosp_aid",fosp_gender:"gender",loc_zone:"lz",loc_country:"lc",loc_province:"lp",eclick_url:"url",eclick_ad_host:"host",eclick_device:"device",eclick_pv:"pv",eclick_debug:"debug",eclick_channel:"chnl",eclick_random:"rand",eclick_start_time:"ts",eclick_version:"v",eclick_os:"os"},Da=function(a,b){for(var c=1,d=arguments.length;c<d;++c)a.push(arguments[c]);return a.length},Ea=function(a,c){var d,e,g,h,k;try{d=x.zone.toString()||b.fosp_location_zone,e=x.country.toString()||
b.fosp_country,g=x.province.toString()||b.fosp_location,h=x.ip.toString()||b.fosp_ip,k=x.isp.toString()||b.fosp_isp}catch(m){}try{y.flash=ta()}catch(n){y.flash="0"}var q=[];M(y,function(a,b){q.push(b+"="+a)});a.eclick_support=q.join("&");a.eclick_debug="0";a.loc_zone=d;a.loc_country=e;a.loc_province=g;a.loc_ip=h;a.loc_isp=k;a.eclick_random=~~((new Date).getTime()/100);a.eclick_channel=f.cookies("channel")?f.cookies("channel"):"0";a.eclick_os=ya();var s={};M(oa,function(b,c){s[b]=void 0!=a[c]?a[c]:
""});d=[];e="VN"+a.eclick_ad_width+a.eclick_ad_height;for(g=0;h=Y[g];g++)if(-1<h.indexOf(e)){Y.splice(g,1);d.push(h);break}if(!sa(a[p.eh])){d=a[p.eh].profile;"undefined"!=typeof d.fosp_code&&""!==d.fosp_code&&(s[oa.fosp_aid]=d.fosp_code);"undefined"!=typeof d.myvne_id&&""!==d.myvne_id&&(s.mvne=d.myvne_id);try{"undefined"!=typeof a.upf&&(s.upf=u(a.upf))}catch(r){}a.eclick_debug="1";var u=function(a){if("string"==typeof a)return a;var b=[],c={};try{c="object"==S(a)&&a.segment||JSON.parse&&JSON.parse(a).segment}catch(d){}for(var f in c)"object"==
S(c[f])&&c[f].id&&b.push(c[f].id);return b.join(",")}}var u=c.slice(-1),w="?"==u||"#"==u?"":"&",v=[c];M(s,function(a,b){if(a||""==a||0===a||!1===a)"boolean"==typeof a&&(a=a?1:0),Da(v,w,b,"=",a),w="&"});return v.join("")},pa=function(f,e){for(var g=f.attributes,l=g.length,k=0;k<l;k++){var m=g[k],n;if(/data-/.test(m.name)){var u=m.name.replace("data","eclick").replace(/-/g,"_");e.hasOwnProperty(u)||(n=m.value,null===n||(e[u]=n))}}e[p.eh]=a(e);e[p.st]=G;e[p.rf]=U(D.document.referrer+"");e[p.pv]=h;e[p.uv]=
320771303;e[p.aa]=!0;e[p.vs]="4";x&&(g=x[p.mi]&&x[p.mi].replace(/"/g,""),l=x[p.oi]&&x[p.oi].replace(/"/g,""),e[p.gd]=x.fosp_gender,e[p.vi]=x.fosp_aid.replace(/"/g,""),e[p.oi]=l,e[p.my]=g,e[p.lc]=x.country,e[p.lp]=x.province,e[p.lz]=x.zone,e[p.li]=x.ip,e[p.lis]=x.isp);e[p.dv]=ja()?ia()?"3":"2":"1";g=p.ul;l=la.document.location;k=la.document.referrer;l=(l=ga()?k:l.href)&&"false"!=l.toString()&&"boolean"!=S(l)?l:ga()?d.referrer:d.location.href;e[g]=U(l);var g=p.ah,r;try{r=ga()?d.referrer.match(/\/[^\/:]+/)[0].substr(1):
c.href.match(/\/[^\/:]+/)[0].substr(1)}catch(w){r=""}e[g]=U(r);f.setAttribute("data-adsbyeclick","done");if(""!=e.zone){r=b;r.eclick_unique_id?r.eclick_unique_id++:r.eclick_unique_id=1;e.eclick_pvUrl=da(e,B("t.eclick.vn","/pageview?"),!1);e.eclick_batchUrl=Ea(e,B("g.eclick.vn","/delivery/zone/batch.json?"));"1"===e.eclick_ad_ivid&&(r=B("g.eclick.vn","/video.xml?"),g=[],g.push("url="+e.eclick_url),g.push("fosp_aid="+(e.fosp_aid?e.fosp_aid:"")),g.push("pv="+e.eclick_pv),g.push("sw="+e.eclick_ad_width),
g.push("sh="+e.eclick_ad_height),r+=g.join("&"),e.eclick_xmlUrl=r);"undefined"!=typeof e.retar_u23&&(e.eclick_batchUrl+="&retargeting_id=retar_u23:"+e.retar_u23);r={tt_article_id:["3723749","3813099"],tt_category_id:["1004174","1004175","1004176","1004177","1004178"]};g=!0;s||"number"!=typeof articleAds||1!=articleAds||(g=!1);for(var v in r)if(-1<r[v].indexOf(Fa[v]||"")){g=!1;break}0<=(q.location.href+"").indexOf("/nong-nghiep-sach")&&(v=f.parentNode.parentNode.parentNode,v.classList.contains("banner_mobile_300x250")&&
(v.parentNode.style.display="none"),g=!1);g&&Ca(e,f)}},Fa=function(){for(var a={},b=d.getElementsByTagName("meta"),c=0,e=b.length,f=b[c];c<e;f=b[++c]){var g=f.getAttribute("name"),f=f.getAttribute("content");null!=g&&(a[g]=f)}return a}(),qa=function(){var a,c;if((a=b.adsbyeclick)&&a.shift)for(var d=20;(c=a.shift())&&0<d--;)try{a:{var e=c.element;if(e){if(!ha(e)&&(e=e.id&&na(e.id),!e)){b.document.createComment&&e.appendChild(b.document.createComment("adsbyeclick: 'element' has already been filled."));
break a}if(!("innerHTML"in e))break a}else if(e=na(),!e)break a;pa(e,c)}}catch(f){throw b.setTimeout(qa,0),f;}a&&a.loaded||(b.adsbyeclick={push:Ga,loaded:!0});Aa()},Ga=function(){for(var a=document.getElementsByTagName("ins"),b=0,c=a[b];b<a.length;c=a[++b])ha(c)&&pa(c,{});return null};qa()}})()}})(window);
