try{(function(f,h,y,l){(function(){if("undefined"!==typeof localStorage)try{return localStorage.setItem("egguuu","yes"),"yes"===localStorage.getItem("egguuu")?(localStorage.removeItem("egguuu"),!0):!1}catch(a){return!1}else return!1})();var H=f.encodeURIComponent,K=f.decodeURIComponent,T=unescape,I=navigator,L=function(a,b){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="json";d.onload=function(){var a=d.status;200===a?b(null,d.response):b(a,d.response)};d.onerror=function(){b("error",
{})};d.send()},n=function(a){return(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(h.cookie))?K(a[2]):""},m=function(a,b,d,c){var e=document.domain.split(".");!d&&(d=0);!c&&(c=31449600);if(1<e.length&&b)for(var f="."+e[e.length-1],g=e.length-2;0<=g;g--){f="."+e[g]+f;var p=void 0,l=a,m=b,u=c,k=f;u&&(p=new Date,p.setTime(p.getTime()+1E3*u));h.cookie=l+"="+H(m)+(u?";expires="+p.toGMTString():"")+";path=/"+(k?";domain="+k:"");if(n(a)==b){0==d&&(d=window,e=window.name,f=a,g=b,-1<e.indexOf("&"+f+"=")||0===
e.indexOf(f+"=")?(p=e.indexOf("&"+f+"="),-1===p&&(p=e.indexOf(f+"=")),c=e.indexOf("&",p+1),c=-1!==c?e.substr(0,p)+e.substr(c+(p?0:1))+"&"+f+"="+g:e.substr(0,p)+"&"+f+"="+g):c=e+"&"+f+"="+g,d.name=c,window.localStorage&&"function"==typeof window.localStorage.setItem&&window.localStorage.setItem(a,b));break}}};l=function(){L("https://g.eclick.vn/iplocation",function(a,b){if(""==n("fosp_loc"))if(b.data&&b.data.country_code)z=[b.data.province_id,b.data.region_id,b.data.country_code].join("-"),m("fosp_loc",
z,0,86400);else{var d="https://ipinfo.io/json";b.ip&&(d="https://ipinfo.io/"+b.ip+"/json");L(d,function(a,b){b.region&&b.country&&""==n("fosp_loc")&&(z=[b.region,"0",b.country].join("-"),m("fosp_loc",z,0,86400))})}})};var z=n("fosp_loc");""==z&&l();var C=function(a){var b=n(a)||"",d=(new RegExp("(^|&)[ ]*"+a+"=([^&]*)","i")).exec(window.name);d=d&&2<d.length&&window.decodeURIComponent(d[2])||"";var c="";window.localStorage&&"function"==typeof window.localStorage.getItem&&(c=window.localStorage.getItem(a));
return b||c||d},M="---",N=function(){for(var a="",b=0;16>b;b++)a+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));return a=a+"."+Math.floor((new Date).getTime()/1E3)};l=function(a){if(h.cookie!=M||2==a){M=h.cookie;var b=parseInt("0"+n("myvne_user_id"))||0,d=n("fosp_aid"),c=n("orig_aid");a=C("fosp_aid")||"";var e=C("orig_aid")||"";if(1E4<b)d!=b&&(m("fosp_aid",b),d!=c&&(e=12<a.length?a:12<e.length?e:N(),m("orig_aid",e)));else if(""!=a&&a==parseInt("0"+a))m("fosp_aid",e);
else if(""!=e&&e!=parseInt("0"+e))m("fosp_aid",e),m("orig_aid",e);else if(d!=c||""==d||""==c)b=12<a.length?a:12<e.length?e:N(),a!=b&&m("fosp_aid",b),e!=b&&m("orig_aid",b)}};"undefined"==typeof window.FospAnalyticsNew&&(f.setInterval(l,1E3),l(2));var D=!1,E=f._logEgg||(f._logEgg=[]);l=f.PAGE_DETAIL||0;a:{if(I=this.navigator)if(y=I.userAgent){var J=y;break a}J=""}var F=function(a){return-1!=J.toLowerCase().indexOf(a.toLowerCase())},O=function(a){var b=function(a,b){return a<<b|a>>>32-b},d=function(a){var b=
"",c;for(c=7;0<=c;c--)b+=(a>>>4*c&15).toString(16);return b},c,e=[],f=1732584193,g=4023233417,p=2562383102,h=271733878,l=3285377520,u=[];a=T(H(a));var k=a.length;for(c=0;c<k-3;c+=4){var q=a.charCodeAt(c)<<24|a.charCodeAt(c+1)<<16|a.charCodeAt(c+2)<<8|a.charCodeAt(c+3);u.push(q)}switch(k&3){case 0:c=2147483648;break;case 1:c=a.charCodeAt(k-1)<<24|8388608;break;case 2:c=a.charCodeAt(k-2)<<24|a.charCodeAt(k-1)<<16|32768;break;case 3:c=a.charCodeAt(k-3)<<24|a.charCodeAt(k-2)<<16|a.charCodeAt(k-1)<<8|
128}for(u.push(c);14!==(u.length&15);)u.push(0);u.push(k>>>29);u.push(k<<3&4294967295);for(a=0;a<u.length;a+=16){for(c=0;16>c;c++)e[c]=u[a+c];for(c=16;79>=c;c++)e[c]=b(e[c-3]^e[c-8]^e[c-14]^e[c-16],1);q=f;k=g;var r=p,t=h,m=l;for(c=0;19>=c;c++){var n=b(q,5)+(k&r|~k&t)+m+e[c]+1518500249&4294967295;m=t;t=r;r=b(k,30);k=q;q=n}for(c=20;39>=c;c++)n=b(q,5)+(k^r^t)+m+e[c]+1859775393&4294967295,m=t,t=r,r=b(k,30),k=q,q=n;for(c=40;59>=c;c++)n=b(q,5)+(k&r|k&t|r&t)+m+e[c]+2400959708&4294967295,m=t,t=r,r=b(k,30),
k=q,q=n;for(c=60;79>=c;c++)n=b(q,5)+(k^r^t)+m+e[c]+3395469782&4294967295,m=t,t=r,r=b(k,30),k=q,q=n;f=f+q&4294967295;g=g+k&4294967295;p=p+r&4294967295;h=h+t&4294967295;l=l+m&4294967295}n=d(f)+d(g)+d(p)+d(h)+d(l);return n.toLowerCase()},W=function(a,b,d){return a.call.apply(a.bind,arguments)},X=function(a,b,d){if(!a)throw Error();if(2<arguments.length){var c=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,c);return a.apply(b,
d)}}return function(){return a.apply(b,arguments)}},w=function(a,b,d){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?W:X;return w.apply(null,arguments)},x=function(a,b,d,c){a.addEventListener?a.addEventListener(b,d,!!c):a.attachEvent?a.attachEvent("on"+b,d):a["on"+b]=d},A=function(a,b,d,c){a.removeEventListener?a.removeEventListener(b,d,!!c):a.detachEvent?a.detachEvent("on"+b,d):a["on"+b]=null},P=function(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);
return b?b[1]:a},Y=function(a,b){var d=new Image(1,1);if(b){var c=function(a){b(a);A(d,"load",c,!1);A(d,"error",c,!1)};x(d,"load",c,!1);x(d,"error",c,!1)}d.src=a};y=function(a){var b;h.addEventListener?x(h,"DOMContentLoaded",function c(){A(h,"DOMContentLoaded",c,!1);a()},!1):h.attachEvent&&(x(h,"onreadystatechange",function e(){"complete"===h.readyState&&(A(h,"onreadystatechange",e,!1),a())},!1),h.documentElement.doScroll&&f===f.top&&function U(){if(!D){try{h.documentElement.doScroll("left")}catch(V){setTimeout(U,
0);return}a()}}());/WebKit/.test(I.userAgent)&&(b=setInterval(function(){if(D||/loaded|complete/.test(h.readyState))clearInterval(b),a()},10));x(f,"load",a,!1)};var Q=function(a){var b={},d;for(d in a)if(a.hasOwnProperty(d)){var c=a[d],e=typeof c;b[d]="function"===e||"object"===e&&c?Q(a[d]):a[d]}return b},R=function(a){return null===a?!1:"function"===typeof a||"object"===typeof a},B=function(){this.location_url=f.location_url||f.location.href;this.site_id=parseInt("0"+f.SITE_ID);this.pageview_id=
this.my_vne=this.fosp_loc=this.fosp_aid=this.uid=null;this.meta={};this.article_id=0;this.action_name="profile_update play pageview buy addtocart checkout read like comment save fblike fbshare twitter ggplus".split(" ");this.action="pageview";this.host=this.referer=this.link_ref=null;this.platform="1";this.algoRead=this.totalRead=this.readStart=0;this.scrollEvent=!1;this.scrollTimer=0;this.container=null;this.type="text";this.playEmbed=0;this.logEggType={ts_1:0,ts_2:0,ts_3:0,ts_4:0,ts_5:0,ts_6:0,
ts_7:0,ts_8:0,ts_9:0,ts_10:0};this.vnTracking=function(){for(var a=f.dataLayer||{},b=0;b<a.length;b++){var d=a[b],c;for(c in d)if("vn_source"==c||"vn_campaign"==c||"vn_medium"==c)this.meta[c]=d[c]}};this.init=function(){var a=C("fosp_aid"),b=C("orig_aid");if(!a||""==a){var d;if(d=/(^|&)[ ]*fosp_aid=([^&]*)/.exec(f.name))a=K(d[2]);else{d="";for(a=0;16>a;a++)d+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));a=d+"."+Math.floor((new Date).getTime()/1E3)}}this.fosp_aid=a.substr(0,
40);this.uid=b?b.substr(0,40):this.fosp_aid;this.fosp_loc=z;this.my_vne=n("myvne_user_id");this.pageview_id=O(Math.random()+this.fosp_aid+Date.now()).substr(0,32);d={};a=h.getElementsByTagName("meta");b=0;for(var c=a.length,e=a[b];b<c;e=a[++b]){var g=e.getAttribute("name");e=e.getAttribute("content");null!=g&&(d[g]=e)}this.meta=d;this.article_id=this.meta.its_id||0;this.ref_id=this.meta.its_ref||0;d="";try{d=f.top.document.referrer}catch(V){if(f.parent)try{d=f.parent.document.referrer}catch(p){d=
""}}""===d&&(d=h.referrer);this.link_ref=d;this.referer=P(d);this.host=P(f.location.href);/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/i.test(J)&&(this.platform="2",F("iPad")||F("Android")&&!F("Mobile")||F("Silk"))&&(this.platform="3");this.meta.hasOwnProperty("its_type")&&(this.type=this.meta.its_type||"text");this.vnTracking()};this.eventBeforeUnLoad=function(a){f.setTimeout(w(this.actualRead,
this),0);return!0};this.actualRead=function(){var a=Date.now();if(0<this.readStart){this.algoRead+=a-this.readStart;var b=Math.min(100,Math.floor(100*this.algoRead/this.totalRead));b=Math.floor(b/10);this.logEggType.hasOwnProperty("ts_"+b)&&!this.logEggType["ts_"+b]&&(this.logEggType["ts_"+b]=1,this.sendLog({action:"read",ratio:10*b}));10==b&&(this.scrollEvent&&f.clearTimeout(this.scrollEvent),A(f,"scroll",S,!1))}this.readStart=a};this.eventVideo=function(a){if(a.detail&&a.detail.type){var b=0;switch(a.detail.type){case "videoComplete":b=
100;break;case "videoStart":b=0;break;case "videoPlay":b=0;break;case "videoProgress":b=(""+(a.detail&&a.detail.percent)).replace("%",""),b=1*parseInt(b)}a=Math.floor(.1*b);this.logEggType.hasOwnProperty("ts_"+a)&&!this.logEggType["ts_"+a]&&(this.logEggType["ts_"+a]=1,this.sendLog({action:"play",type:"video",ratio:b}))}};this.eventInterval=function(){if("video"==this.type||"play"==this.action)return!1;var a=!0;3>this.scrollTimer?0<this.readStart&&(this.scrollEvent&&f.clearTimeout(this.scrollEvent),
this.scrollEvent=f.setTimeout(w(this.eventInterval,this),5E3)):a=!1;this.actualRead();a||(this.readStart=0);this.scrollTimer+=1};this.eventScroll=function(){this.scrollTimer=0;var a=!1;if(this.container){var b=this.container.getBoundingClientRect();b&&b.top<f.innerHeight&&0<b.bottom?a=!0:this.readStart=0}a&&(this.scrollEvent&&f.clearTimeout(this.scrollEvent),this.scrollEvent=f.setTimeout(w(this.eventInterval,this),500))};this.initReady=function(){var a=this.meta.hasOwnProperty("its_wordcount")&&parseInt(this.meta.its_wordcount,
10)||0;if("video"==this.type||"play"==this.action)this.totalRead=0<a?1E3*a:0,x(f,"PlayerCustomEvent",w(this.eventVideo,this),!1);else{var b=h.getElementsByClassName("block_ads_connect");0==b.length&&(b=h.getElementsByClassName("fck_detail"),0==b.length&&(b=h.getElementsByTagName("body")));0<b.length&&b[0].innerText&&(this.container=b[0],b=b[0].innerText.match(/[\w\.]+?([\.']\w+?)?([\s\.',\):\]]+|$)/gi).length,b=Math.max(b,a),this.totalRead=1E3*Math.round(b/(200<b?5:6)))}1>this.totalRead&&(this.totalRead=
1);this.readStart=Date.now();this.eventInterval()}};B.prototype.sendLog=function(a){var b;a.hasOwnProperty("action")&&(b=-1<this.action_name.indexOf(a.action)?a.action:null);if(b){for(var d=this.meta,c="vn_source vn_medium vn_campaign its_name its_url its_id its_title its_section its_subsection its_tag its_topic its_object its_embed its_author its_type its_wordcount its_publication".split(" "),e=0,f=c.length;e<f;e++){var g=c[e];d.hasOwnProperty(g)&&(a[g]=d[g])}a.platform=this.platform;a.fosp_loc=
this.fosp_loc;a.referer=this.referer;a.link_ref=this.link_ref;a.location_url=this.location_url;a.site_id=this.site_id;d=[];delete a.its_id;delete a.its_ref;for(var h in a)R(a[h])||d.push(h+"="+H(a[h]));if(1>this.article_id&&-1<" play pageview buy addtocart checkout read like comment save fblike fbshare twitter ggplus".indexOf(a.action))return!1;d.push("its_id="+this.article_id);d.push("its_ref="+this.ref_id);d.push("fosp_aid="+this.fosp_aid);d.push("uid="+this.uid);d.push("my_vne="+this.my_vne);d.push("play_embed="+
this.playEmbed);d.push("pageview_id="+this.pageview_id);Y("https://la3.vnecdn.net/"+b+"/?"+d.join("&"),function(){});return!0}};if(E.push===Array.prototype.push){var g=new B;g.init();g.sendLog({action:"pageview"});if(l){var S=w(g.eventScroll,g);y(function(){D||(g.initReady(),x(f,"scroll",S,!1));D=!0})}var v={egg:g},G=function(a){var b="play"==a.action?"play":"egg",d=a.meta&&a.meta.its_id||a.id||g.article_id;b=d==g.article_id?b:b+d;if(!(v[b]&&v[b]instanceof B)){var c=new B;c.action=a.action;c.playEmbed=
a.play_embed||0;c.fosp_aid=g.fosp_aid;c.uid=g.uid;c.fosp_loc=g.fosp_loc;c.my_vne=g.my_vne;c.pageview_id="pageview"==a.action?O(Math.random()+g.fosp_aid+Date.now()).substr(0,32):g.pageview_id;c.meta=g.meta;c.article_id=d;c.ref_id=g.article_id;c.referer=g.host;c.link_ref=g.link_ref;c.location_url="pageview"==a.action?f.location.href:g.location_url;c.platform=g.platform;if(a.meta&&R(a.meta))for(var e in a.meta)c.meta[e]=a.meta[e];c.vnTracking();c.type=a.meta&&a.meta.its_type?a.meta.its_type:g.type;for(var h in v)v.hasOwnProperty(h)&&
v[h]instanceof B&&v[h].type==c.type&&(v[h].logEggType={});c.initReady();v[b]=c}return v[b]};y=function(a){if("[object Object]"!==Object.prototype.toString.call(a))return!1;G(a).sendLog(a);return 1};l=0;for(var Z=E.length;l<Z;++l)y(E[l]);E.push=function(a){G(a).sendLog(a);"pageview"==a.action&&a.meta&&"video"==a.meta.its_type&&(a=Q(a),a.action="play",a.ratio=0,G(a).sendLog(a))};1003834==f.SITE_ID&&"pageview"==g.action&&"video"==g.type&&(l={action:"play",ratio:0},G(l).sendLog(l))}})(window,document,
location,history)}catch(f){console.log("egg:",f)};